/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */

export type AdminSearchResourceOwnersParams = {
    types?: string | null;
    include_ids?: string | null;
    /**
     * @maxLength 100
     */
    keyword?: string | null;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number | null;
};
