/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { AdminSearchCompanies200MetaLinksItemUrl } from './adminSearchCompanies200MetaLinksItemUrl';

export type AdminSearchCompanies200MetaLinksItem = {
    url: AdminSearchCompanies200MetaLinksItemUrl;
    label: string;
    active: boolean;
};
