/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { AdminSearchCompanies200LinksFirst } from './adminSearchCompanies200LinksFirst';
import type { AdminSearchCompanies200LinksLast } from './adminSearchCompanies200LinksLast';
import type { AdminSearchCompanies200LinksNext } from './adminSearchCompanies200LinksNext';
import type { AdminSearchCompanies200LinksPrev } from './adminSearchCompanies200LinksPrev';

export type AdminSearchCompanies200Links = {
    first: AdminSearchCompanies200LinksFirst;
    last: AdminSearchCompanies200LinksLast;
    prev: AdminSearchCompanies200LinksPrev;
    next: AdminSearchCompanies200LinksNext;
};
