/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { SearchResourceOwnersResource } from './searchResourceOwnersResource';

export type AdminSearchResourceOwners200 = {
  data: SearchResourceOwnersResource;
};
