/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { AffiliateProfileResourceAddress } from './affiliateProfileResourceAddress';
import type { AffiliateProfileResourceApprovedAt } from './affiliateProfileResourceApprovedAt';
import type { AffiliateProfileResourceCityId } from './affiliateProfileResourceCityId';
import type { AffiliateProfileResourceCreatedAt } from './affiliateProfileResourceCreatedAt';
import type { AffiliateProfileResourceDistrictId } from './affiliateProfileResourceDistrictId';
import type { AffiliateProfileResourceIdentityCardId } from './affiliateProfileResourceIdentityCardId';
import type { AffiliateProfileResourceIdentityNumber } from './affiliateProfileResourceIdentityNumber';
import type { AffiliateProfileResourcePhone } from './affiliateProfileResourcePhone';
import type { AffiliateProfileResourcePhotoId } from './affiliateProfileResourcePhotoId';
import type { AffiliateProfileResourcePostalCode } from './affiliateProfileResourcePostalCode';
import type { AffiliateProfileResourceProvinceId } from './affiliateProfileResourceProvinceId';
import type { AffiliateProfileResourceUpdatedAt } from './affiliateProfileResourceUpdatedAt';
import type { AffiliateProfileResourceUplineId } from './affiliateProfileResourceUplineId';
import type { AffiliateProfileResourceVillageId } from './affiliateProfileResourceVillageId';

export interface AffiliateProfileResource {
    id: number;
    user_id: number;
    upline_id: AffiliateProfileResourceUplineId;
    tier: string;
    status: string;
    phone: AffiliateProfileResourcePhone;
    address: AffiliateProfileResourceAddress;
    province_id: AffiliateProfileResourceProvinceId;
    city_id: AffiliateProfileResourceCityId;
    district_id: AffiliateProfileResourceDistrictId;
    village_id: AffiliateProfileResourceVillageId;
    postal_code: AffiliateProfileResourcePostalCode;
    identity_number: AffiliateProfileResourceIdentityNumber;
    referral_code: string;
    approved_at: AffiliateProfileResourceApprovedAt;
    created_at: AffiliateProfileResourceCreatedAt;
    updated_at: AffiliateProfileResourceUpdatedAt;
    photo_id: AffiliateProfileResourcePhotoId;
    identity_card_id: AffiliateProfileResourceIdentityCardId;
    photo_url: string;
    identity_card_url: string;
}
