/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { AiModelResourceCreatedAt } from './aiModelResourceCreatedAt';
import type { AiModelResourceUpdatedAt } from './aiModelResourceUpdatedAt';

export interface AiModelResource {
  id: number;
  code: boolean;
  input_token_rate: string;
  output_token_rate: string;
  created_at: AiModelResourceCreatedAt;
  updated_at: AiModelResourceUpdatedAt;
}
