/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { AnonymousUserResourceCreatedAt } from './anonymousUserResourceCreatedAt';
import type { AnonymousUserResourceUpdatedAt } from './anonymousUserResourceUpdatedAt';

export interface AnonymousUserResource {
  id: number;
  token: string;
  created_at: AnonymousUserResourceCreatedAt;
  updated_at: AnonymousUserResourceUpdatedAt;
}
