/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { BankAccountResourceBranch } from './bankAccountResourceBranch';
import type { BankAccountResourceCreatedAt } from './bankAccountResourceCreatedAt';

export interface BankAccountResource {
    id: number;
    provider: string;
    account_number: string;
    account_name: string;
    branch: BankAccountResourceBranch;
    status: string;
    is_default: boolean;
    created_at: BankAccountResourceCreatedAt;
}
