/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { BankAccountResourceBranch } from './bankAccountResourceBranch';
import type { BankAccountResourceCreatedAt } from './bankAccountResourceCreatedAt';

export interface BankAccountResource {
  id: number;
  provider: string;
  account_number: string;
  account_name: string;
  branch: BankAccountResourceBranch;
  status: string;
  is_default: boolean;
  created_at: BankAccountResourceCreatedAt;
}
