/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CategoriesStoreBodyDescription } from './categoriesStoreBodyDescription';
import type { CategoriesStoreBodyUserId } from './categoriesStoreBodyUserId';

export type CategoriesStoreBody = {
  /** @maxLength 255 */
  name: string;
  description?: CategoriesStoreBodyDescription;
  position_no: string;
  user_id?: CategoriesStoreBodyUserId;
};
