/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { CategoriesUpdateBodyDescription } from './categoriesUpdateBodyDescription';
import type { CategoriesUpdateBodyUserId } from './categoriesUpdateBodyUserId';

export type CategoriesUpdateBody = {
  /** @maxLength 255 */
  name?: string;
  description?: CategoriesUpdateBodyDescription;
  user_id?: CategoriesUpdateBodyUserId;
};
