/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { TourCategoryResource } from './tourCategoryResource';

export type CategoriesShow200 = {
  data: TourCategoryResource;
};
