/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ChatRoomResourceLastMessageAttachmentData } from './chatRoomResourceLastMessageAttachmentData';
import type { ChatRoomResourceLastMessageAttachmentType } from './chatRoomResourceLastMessageAttachmentType';
import type { ChatRoomResourceLastMessageCreatedAt } from './chatRoomResourceLastMessageCreatedAt';
import type { ChatRoomResourceLastMessageMessage } from './chatRoomResourceLastMessageMessage';
import type { ChatRoomResourceLastMessageUserId } from './chatRoomResourceLastMessageUserId';

export type ChatRoomResourceLastMessage = {
    id: number;
    message: ChatRoomResourceLastMessageMessage;
    user_id: ChatRoomResourceLastMessageUserId;
    created_at: ChatRoomResourceLastMessageCreatedAt;
    is_bot: boolean;
    attachment_data: ChatRoomResourceLastMessageAttachmentData;
    attachment_type: ChatRoomResourceLastMessageAttachmentType;
};
