/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type ChatRoomResourceCreator = {
    id: string;
    name: string;
    photo_url: string;
};
