/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ChatMessageResourceRoomName } from './chatMessageResourceRoomName';

export type ChatMessageResourceRoom = {
  id: number;
  name: ChatMessageResourceRoomName;
};
