/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ChatRoomMemberLastReadAt } from './chatRoomMemberLastReadAt';
import type { ChatRoomMemberCreatedAt } from './chatRoomMemberCreatedAt';
import type { ChatRoomMemberUpdatedAt } from './chatRoomMemberUpdatedAt';
import type { ChatRoomMember as __ChatRoomMember } from './chatRoomMember';

export interface ChatRoomMember {
  id: number;
  room_id: number;
  member_type: string;
  member_id: number;
  role: string;
  joined_at: string;
  last_read_at: ChatRoomMemberLastReadAt;
  created_at: ChatRoomMemberCreatedAt;
  updated_at: ChatRoomMemberUpdatedAt;
  member?: __ChatRoomMember;
}
