/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ChatMessageResourceReplyToAnyOf } from './chatMessageResourceReplyToAnyOf';

export type ChatMessageResourceReplyTo = ChatMessageResourceReplyToAnyOf | null;
