/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ChatMessageResourceSenderAnyOfPhotoUrl } from './chatMessageResourceSenderAnyOfPhotoUrl';

/**
 * Relationships
 */
export type ChatMessageResourceSenderAnyOf = {
  id: number;
  name: string;
  photo_url: ChatMessageResourceSenderAnyOfPhotoUrl;
};
