/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ChatMessageResourceAttachment } from './chatMessageResourceAttachment';
import type { ChatMessageResourceAttachmentType } from './chatMessageResourceAttachmentType';
import type { ChatMessageResourceCreatedAt } from './chatMessageResourceCreatedAt';
import type { ChatMessageResourceUpdatedAt } from './chatMessageResourceUpdatedAt';
import type { ChatMessageResourceSender } from './chatMessageResourceSender';
import type { ChatMessageResourceRoom } from './chatMessageResourceRoom';
import type { ChatMessageResourceReplyTo } from './chatMessageResourceReplyTo';

export interface ChatMessageResource {
  id: number;
  room_id: number;
  sender_id: number;
  message: string;
  attachment: ChatMessageResourceAttachment;
  attachment_type: ChatMessageResourceAttachmentType;
  created_at: ChatMessageResourceCreatedAt;
  updated_at: ChatMessageResourceUpdatedAt;
  /** Relationships */
  sender: ChatMessageResourceSender;
  room: ChatMessageResourceRoom;
  replyTo: ChatMessageResourceReplyTo;
  /** @minimum 0 */
  replies_count: number;
}
