/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { ChatRoomMember } from './chatRoomMember';
import type { ChatRoomResourceCreatedAt } from './chatRoomResourceCreatedAt';
import type { ChatRoomResourceLastMessage } from './chatRoomResourceLastMessage';
import type { ChatRoomResourceName } from './chatRoomResourceName';
import type { ChatRoomResourceUpdatedAt } from './chatRoomResourceUpdatedAt';

export interface ChatRoomResource {
    id: number;
    name: ChatRoomResourceName;
    type: string;
    created_by: string;
    created_at: ChatRoomResourceCreatedAt;
    updated_at: ChatRoomResourceUpdatedAt;
    last_message?: ChatRoomResourceLastMessage;
    members?: ChatRoomMember[];
}
