/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ChatRoomResourceLastMessageUserId } from './chatRoomResourceLastMessageUserId';
import type { ChatRoomResourceLastMessageCreatedAt } from './chatRoomResourceLastMessageCreatedAt';
import type { ChatRoomResourceLastMessageAttachment } from './chatRoomResourceLastMessageAttachment';
import type { ChatRoomResourceLastMessageAttachmentType } from './chatRoomResourceLastMessageAttachmentType';

export type ChatRoomResourceLastMessage = {
  id: number;
  message: string;
  user_id: ChatRoomResourceLastMessageUserId;
  created_at: ChatRoomResourceLastMessageCreatedAt;
  is_bot: string;
  attachment: ChatRoomResourceLastMessageAttachment;
  attachment_type: ChatRoomResourceLastMessageAttachmentType;
};
