/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

/**
 * Relationships
 */
export type ChatMessageResourceSender = {
  id: number;
  name: string;
  photo_url: string;
};
