/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ChatMessageResourceRoomAnyOfName } from './chatMessageResourceRoomAnyOfName';

export type ChatMessageResourceRoomAnyOf = {
  id: number;
  name: ChatMessageResourceRoomAnyOfName;
};
