/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CompanyCityId } from './companyCityId';
import type { CompanyCreatedAt } from './companyCreatedAt';
import type { CompanyDistrictId } from './companyDistrictId';
import type { CompanyIdentityCardId } from './companyIdentityCardId';
import type { CompanyIdentityNumber } from './companyIdentityNumber';
import type { CompanyLogoId } from './companyLogoId';
import type { CompanyMeta } from './companyMeta';
import type { CompanyNote } from './companyNote';
import type { CompanyPhotoId } from './companyPhotoId';
import type { CompanyPostalCode } from './companyPostalCode';
import type { CompanyProvinceId } from './companyProvinceId';
import type { CompanyReferredBy } from './companyReferredBy';
import type { CompanyRememberToken } from './companyRememberToken';
import type { CompanyType } from './companyType';
import type { CompanyUpdatedAt } from './companyUpdatedAt';
import type { CompanyVillageId } from './companyVillageId';

export interface Company {
    id: number;
    type: CompanyType;
    name: string;
    username: string;
    email: string;
    address: string;
    phone: string;
    customer_service_phone: string;
    province_id: CompanyProvinceId;
    city_id: CompanyCityId;
    district_id: CompanyDistrictId;
    village_id: CompanyVillageId;
    postal_code: CompanyPostalCode;
    identity_number: CompanyIdentityNumber;
    note: CompanyNote;
    meta: CompanyMeta;
    remember_token: CompanyRememberToken;
    created_at: CompanyCreatedAt;
    updated_at: CompanyUpdatedAt;
    logo_id: CompanyLogoId;
    photo_id: CompanyPhotoId;
    identity_card_id: CompanyIdentityCardId;
    referred_by: CompanyReferredBy;
    payment_mode: string;
    commission: number;
    photo_url: string;
}
