/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CompanyRememberToken } from './companyRememberToken';
import type { CompanyCreatedAt } from './companyCreatedAt';
import type { CompanyUpdatedAt } from './companyUpdatedAt';

export interface Company {
  id: number;
  type: string;
  name: string;
  username: string;
  email: string;
  address: string;
  phone: string;
  remember_token: CompanyRememberToken;
  created_at: CompanyCreatedAt;
  updated_at: CompanyUpdatedAt;
}
