/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CompanyType } from './companyType';
import type { CompanyResourceProvinceId } from './companyResourceProvinceId';
import type { CompanyResourceCityId } from './companyResourceCityId';
import type { CompanyResourceDistrictId } from './companyResourceDistrictId';
import type { CompanyResourceVillageId } from './companyResourceVillageId';
import type { CompanyResourceDistrict } from './companyResourceDistrict';
import type { CompanyResourceVillage } from './companyResourceVillage';
import type { CompanyResourcePostalCode } from './companyResourcePostalCode';
import type { CompanyResourceIdentityNumber } from './companyResourceIdentityNumber';
import type { CompanyResourceNote } from './companyResourceNote';
import type { CompanyResourceMeta } from './companyResourceMeta';
import type { CompanyResourceRememberToken } from './companyResourceRememberToken';
import type { CompanyResourceCreatedAt } from './companyResourceCreatedAt';
import type { CompanyResourceUpdatedAt } from './companyResourceUpdatedAt';
import type { CompanyResourceLogoId } from './companyResourceLogoId';
import type { CompanyResourcePhotoId } from './companyResourcePhotoId';
import type { CompanyResourceIdentityCardId } from './companyResourceIdentityCardId';
import type { CompanyResourceReferredBy } from './companyResourceReferredBy';

export interface CompanyResource {
  id: number;
  type: CompanyType;
  name: string;
  username: string;
  email: string;
  address: string;
  phone: string;
  customer_service_phone: string;
  province_id: CompanyResourceProvinceId;
  city_id: CompanyResourceCityId;
  district_id: CompanyResourceDistrictId;
  village_id: CompanyResourceVillageId;
  province: string;
  city: string;
  district: CompanyResourceDistrict;
  village: CompanyResourceVillage;
  postal_code: CompanyResourcePostalCode;
  identity_number: CompanyResourceIdentityNumber;
  note: CompanyResourceNote;
  meta: CompanyResourceMeta;
  remember_token: CompanyResourceRememberToken;
  created_at: CompanyResourceCreatedAt;
  updated_at: CompanyResourceUpdatedAt;
  logo_id: CompanyResourceLogoId;
  photo_id: CompanyResourcePhotoId;
  identity_card_id: CompanyResourceIdentityCardId;
  referred_by: CompanyResourceReferredBy;
  payment_mode: string;
  commission: number;
  photo_url: string;
}
