/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CompanyResourceNote } from './companyResourceNote';
import type { CompanyResourceMeta } from './companyResourceMeta';
import type { CompanyResourceRememberToken } from './companyResourceRememberToken';
import type { CompanyResourceCreatedAt } from './companyResourceCreatedAt';
import type { CompanyResourceUpdatedAt } from './companyResourceUpdatedAt';
import type { CompanyResourceLogoId } from './companyResourceLogoId';
import type { CompanyResourcePhotoId } from './companyResourcePhotoId';

export interface CompanyResource {
  id: number;
  type: string;
  name: string;
  username: string;
  subdomain: string;
  email: string;
  address: string;
  phone: string;
  customer_service_phone: string;
  note: CompanyResourceNote;
  meta: CompanyResourceMeta;
  remember_token: CompanyResourceRememberToken;
  created_at: CompanyResourceCreatedAt;
  updated_at: CompanyResourceUpdatedAt;
  logo_id: CompanyResourceLogoId;
  photo_id: CompanyResourcePhotoId;
  photo_url: string;
}
