/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type CompanyType = (typeof CompanyType)[keyof typeof CompanyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompanyType = {
    agent: 'agent',
    vendor: 'vendor',
} as const;
