/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CompanyResourceCityId } from './companyResourceCityId';
import type { CompanyResourceCreatedAt } from './companyResourceCreatedAt';
import type { CompanyResourceDistrictId } from './companyResourceDistrictId';
import type { CompanyResourceIdentityCardId } from './companyResourceIdentityCardId';
import type { CompanyResourceIdentityNumber } from './companyResourceIdentityNumber';
import type { CompanyResourceLogoId } from './companyResourceLogoId';
import type { CompanyResourceMeta } from './companyResourceMeta';
import type { CompanyResourceNote } from './companyResourceNote';
import type { CompanyResourcePhotoId } from './companyResourcePhotoId';
import type { CompanyResourcePostalCode } from './companyResourcePostalCode';
import type { CompanyResourceProvinceId } from './companyResourceProvinceId';
import type { CompanyResourceReferredBy } from './companyResourceReferredBy';
import type { CompanyResourceRememberToken } from './companyResourceRememberToken';
import type { CompanyResourceUpdatedAt } from './companyResourceUpdatedAt';
import type { CompanyResourceVillageId } from './companyResourceVillageId';
import type { CompanyType } from './companyType';

export interface CompanyResource {
    id: number;
    type: CompanyType;
    name: string;
    username: string;
    email: string;
    address: string;
    phone: string;
    customer_service_phone: string;
    province_id: CompanyResourceProvinceId;
    city_id: CompanyResourceCityId;
    district_id: CompanyResourceDistrictId;
    village_id: CompanyResourceVillageId;
    postal_code: CompanyResourcePostalCode;
    identity_number: CompanyResourceIdentityNumber;
    note: CompanyResourceNote;
    meta: CompanyResourceMeta;
    remember_token: CompanyResourceRememberToken;
    created_at: CompanyResourceCreatedAt;
    updated_at: CompanyResourceUpdatedAt;
    logo_id: CompanyResourceLogoId;
    photo_id: CompanyResourcePhotoId;
    identity_card_id: CompanyResourceIdentityCardId;
    referred_by: CompanyResourceReferredBy;
    payment_mode: string;
    commission: number;
    photo_url: string;
}
