/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CompanySettingsCreatedAt } from './companySettingsCreatedAt';
import type { CompanySettingsEmailPaymentGateway } from './companySettingsEmailPaymentGateway';
import type { CompanySettingsLandingPageData } from './companySettingsLandingPageData';
import type { CompanySettingsManualBankTransfer } from './companySettingsManualBankTransfer';
import type { CompanySettingsManualBankTransferAccountName } from './companySettingsManualBankTransferAccountName';
import type { CompanySettingsManualBankTransferAccountNumber } from './companySettingsManualBankTransferAccountNumber';
import type { CompanySettingsPasswordPaymentGateway } from './companySettingsPasswordPaymentGateway';
import type { CompanySettingsTermConditions } from './companySettingsTermConditions';
import type { CompanySettingsUpdatedAt } from './companySettingsUpdatedAt';

export interface CompanySettings {
    id: number;
    company_id: number;
    chatbot_enabled: boolean;
    chatbot_response_style: string;
    chatbot_default_language: string;
    landing_page_data: CompanySettingsLandingPageData;
    booking_deadline: number;
    minimum_down_payment: string;
    minimum_vat: string;
    term_conditions: CompanySettingsTermConditions;
    cancel_refund_term_conditions: CompanySettingsTermConditions;
    booking_entry_time_limit: number;
    manual_bank_transfer: CompanySettingsManualBankTransfer;
    manual_bank_transfer_account_name: CompanySettingsManualBankTransferAccountName;
    manual_bank_transfer_account_number: CompanySettingsManualBankTransferAccountNumber;
    email_payment_gateway: CompanySettingsEmailPaymentGateway;
    password_payment_gateway: CompanySettingsPasswordPaymentGateway;
    created_at: CompanySettingsCreatedAt;
    updated_at: CompanySettingsUpdatedAt;
    full_payment_deadline: number;
    document_completed_deadline: number;
    minimum_down_payment_value: string;
}
