/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CompanySettingsLandingPageData } from './companySettingsLandingPageData';
import type { CompanySettingsCreatedAt } from './companySettingsCreatedAt';
import type { CompanySettingsUpdatedAt } from './companySettingsUpdatedAt';

export interface CompanySettings {
  id: number;
  company_id: number;
  enable_chatbot: string;
  landing_page_data: CompanySettingsLandingPageData;
  created_at: CompanySettingsCreatedAt;
  updated_at: CompanySettingsUpdatedAt;
}
