/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export interface ContinentResource {
  id: number;
  continent: string;
  user_id: number;
}
