/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export interface CountryResource {
  id: number;
  country: string;
  region_id: number;
  continent_id: number;
}
