/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type CreateRegionBody = {
  continent_id: number;
  /** @maxLength 255 */
  name: string;
};
