/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CreateContinentBodyUserId } from './createContinentBodyUserId';

export type CreateContinentBody = {
  /** @maxLength 255 */
  continent: string;
  user_id?: CreateContinentBodyUserId;
};
