/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { CreateTopupPaymentBodyOwnerId } from './createTopupPaymentBodyOwnerId';
import type { CreateTopupPaymentBodyOwnerType } from './createTopupPaymentBodyOwnerType';

export type CreateTopupPaymentBody = {
    owner_type: CreateTopupPaymentBodyOwnerType;
    owner_id: CreateTopupPaymentBodyOwnerId;
    /** @minimum 100000 */
    amount: number;
    payment_method_id: number;
};
