/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { CreateMediaBodyName } from './createMediaBodyName';
import type { CreateMediaBodyDescription } from './createMediaBodyDescription';
import type { CreateMediaBodyType } from './createMediaBodyType';

export type CreateMediaBody = {
  /** @maxLength 255 */
  name?: CreateMediaBodyName;
  description?: CreateMediaBodyDescription;
  type: CreateMediaBodyType;
  data: Blob;
};
