/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CreateAgentSubscriptionPaymentBodyProvider } from './createAgentSubscriptionPaymentBodyProvider';

export type CreateAgentSubscriptionPaymentBody = {
    company_id: number;
    package_id: number;
    provider?: CreateAgentSubscriptionPaymentBodyProvider;
};
