/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
export type CreateAiCreditTopupPaymentBody = {
    company_id: number;
    /** @minimum 1000 */
    amount: number;
    payment_method_id: number;
};
