/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ContinentResource } from './continentResource';

export type CreateContinent201 = {
  data: ContinentResource;
};
