/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CreateTopupPaymentBodyOwnerId } from './createTopupPaymentBodyOwnerId';
import type { CreateTopupPaymentBodyOwnerType } from './createTopupPaymentBodyOwnerType';

export type CreateTopupPaymentBody = {
    owner_type: CreateTopupPaymentBodyOwnerType;
    owner_id: CreateTopupPaymentBodyOwnerId;
    /** @minimum 100000 */
    amount: number;
};
