/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentResource } from './paymentResource';

export type CreateTopupPayment200 = {
  data: PaymentResource;
};
