/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { DeleteChatMessage200Message } from './deleteChatMessage200Message';

export type DeleteChatMessage200 = {
  message: DeleteChatMessage200Message;
};
