/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type DeleteChatRoom200Message =
    (typeof DeleteChatRoom200Message)[keyof typeof DeleteChatRoom200Message];

export const DeleteChatRoom200Message = {
    Chat_room_deleted: 'Chat room deleted',
} as const;
