/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { DeleteChatRoom200Message } from './deleteChatRoom200Message';

export type DeleteChatRoom200 = {
  message: DeleteChatRoom200Message;
};
