/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

export type DeleteChatMessage200Message = typeof DeleteChatMessage200Message[keyof typeof DeleteChatMessage200Message];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteChatMessage200Message = {
  Message_deleted: 'Message deleted',
} as const;
