/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type GetBankAccountsParams = {
owner_type?: 'user' | 'vendor' | 'agent' | null;
owner_id?: number | null;
};
