/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { BankAccountResource } from './bankAccountResource';

export type GetBankAccounts200 = {
  success: boolean;
  data: BankAccountResource[];
};
