/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetChatMessages200LinksFirst } from './getChatMessages200LinksFirst';
import type { GetChatMessages200LinksLast } from './getChatMessages200LinksLast';
import type { GetChatMessages200LinksNext } from './getChatMessages200LinksNext';
import type { GetChatMessages200LinksPrev } from './getChatMessages200LinksPrev';

export type GetChatMessages200Links = {
    first: GetChatMessages200LinksFirst;
    last: GetChatMessages200LinksLast;
    prev: GetChatMessages200LinksPrev;
    next: GetChatMessages200LinksNext;
};
