/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { ChatMessageResource } from './chatMessageResource';
import type { GetChatMessages200Links } from './getChatMessages200Links';
import type { GetChatMessages200Meta } from './getChatMessages200Meta';

export type GetChatMessages200 = {
    data: ChatMessageResource[];
    links: GetChatMessages200Links;
    meta: GetChatMessages200Meta;
};
