/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type GetChatRoomsParams = {
member_type?: 'user' | 'company' | null;
/**
 * Make sure these match your actual types
 */
member_id?: number | null;
cursor?: string | null;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number | null;
};
