/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

export type GetChatMessagesParams = {
cursor?: string | null;
/**
 * Laravel cursor is always a string
 * @minimum 1
 * @maximum 100
 */
per_page?: number | null;
};
