/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetChatRoomsMemberType } from './getChatRoomsMemberType';

export type GetChatRoomsParams = {
    member_type?: GetChatRoomsMemberType;
    /**
     * @minimum 1
     */
    member_id?: number;
    cursor?: string | null;
    /**
     * @minimum 1
     * @maximum 100
     */
    per_page?: number;
};
