/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { CompanyResource } from './companyResource';

export type GetCompanies200 = {
  data: CompanyResource[];
};
