/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

/**
 * The "cursor" that points to the previous set of items.
 */
export type GetChatMessages200MetaPrevCursor = string | null;
