/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetCompanies200LinksFirst } from './getCompanies200LinksFirst';
import type { GetCompanies200LinksLast } from './getCompanies200LinksLast';
import type { GetCompanies200LinksPrev } from './getCompanies200LinksPrev';
import type { GetCompanies200LinksNext } from './getCompanies200LinksNext';

export type GetCompanies200Links = {
  first: GetCompanies200LinksFirst;
  last: GetCompanies200LinksLast;
  prev: GetCompanies200LinksPrev;
  next: GetCompanies200LinksNext;
};
