/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { GetChatMessages200LinksFirst } from './getChatMessages200LinksFirst';
import type { GetChatMessages200LinksLast } from './getChatMessages200LinksLast';
import type { GetChatMessages200LinksPrev } from './getChatMessages200LinksPrev';
import type { GetChatMessages200LinksNext } from './getChatMessages200LinksNext';

export type GetChatMessages200Links = {
  first: GetChatMessages200LinksFirst;
  last: GetChatMessages200LinksLast;
  prev: GetChatMessages200LinksPrev;
  next: GetChatMessages200LinksNext;
};
