/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { ChatRoomResource } from './chatRoomResource';
import type { GetChatRooms200Links } from './getChatRooms200Links';
import type { GetChatRooms200Meta } from './getChatRooms200Meta';

export type GetChatRooms200 = {
  data: ChatRoomResource[];
  links: GetChatRooms200Links;
  meta: GetChatRooms200Meta;
};
