/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetCompanies200LinksFirst } from './getCompanies200LinksFirst';
import type { GetCompanies200LinksLast } from './getCompanies200LinksLast';
import type { GetCompanies200LinksNext } from './getCompanies200LinksNext';
import type { GetCompanies200LinksPrev } from './getCompanies200LinksPrev';

export type GetCompanies200Links = {
    first: GetCompanies200LinksFirst;
    last: GetCompanies200LinksLast;
    prev: GetCompanies200LinksPrev;
    next: GetCompanies200LinksNext;
};
