/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { CompanyResource } from './companyResource';
import type { GetCompanies200Links } from './getCompanies200Links';
import type { GetCompanies200Meta } from './getCompanies200Meta';

export type GetCompanies200 = {
    data: CompanyResource[];
    links: GetCompanies200Links;
    meta: GetCompanies200Meta;
};
