/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetCompanies200MetaFrom } from './getCompanies200MetaFrom';
import type { GetCompanies200MetaLinksItem } from './getCompanies200MetaLinksItem';
import type { GetCompanies200MetaPath } from './getCompanies200MetaPath';
import type { GetCompanies200MetaTo } from './getCompanies200MetaTo';

export type GetCompanies200Meta = {
  /** @minimum 1 */
  current_page: number;
  /** @minimum 1 */
  from: GetCompanies200MetaFrom;
  /** @minimum 1 */
  last_page: number;
  /** Generated paginator links. */
  links: GetCompanies200MetaLinksItem[];
  /** Base path for paginator generated URLs. */
  path: GetCompanies200MetaPath;
  /**
   * Number of items shown per page.
   * @minimum 0
   */
  per_page: number;
  /**
   * Number of the last item in the slice.
   * @minimum 1
   */
  to: GetCompanies200MetaTo;
  /**
   * Total number of items being paginated.
   * @minimum 0
   */
  total: number;
};
