/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { ChatMessageResource } from './chatMessageResource';
import type { GetChatMessages200Links } from './getChatMessages200Links';
import type { GetChatMessages200Meta } from './getChatMessages200Meta';

export type GetChatMessages200 = {
  data: ChatMessageResource[];
  links: GetChatMessages200Links;
  meta: GetChatMessages200Meta;
};
