/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetChatRooms200LinksFirst } from './getChatRooms200LinksFirst';
import type { GetChatRooms200LinksLast } from './getChatRooms200LinksLast';
import type { GetChatRooms200LinksNext } from './getChatRooms200LinksNext';
import type { GetChatRooms200LinksPrev } from './getChatRooms200LinksPrev';

export type GetChatRooms200Links = {
    first: GetChatRooms200LinksFirst;
    last: GetChatRooms200LinksLast;
    prev: GetChatRooms200LinksPrev;
    next: GetChatRooms200LinksNext;
};
