/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

/**
 * The "cursor" that points to the next set of items.
 */
export type GetChatMessages200MetaNextCursor = string | null;
