/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetCompanies200MetaLinksItemUrl } from './getCompanies200MetaLinksItemUrl';

export type GetCompanies200MetaLinksItem = {
  url: GetCompanies200MetaLinksItemUrl;
  label: string;
  active: boolean;
};
