/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { GetChatRooms200LinksFirst } from './getChatRooms200LinksFirst';
import type { GetChatRooms200LinksLast } from './getChatRooms200LinksLast';
import type { GetChatRooms200LinksPrev } from './getChatRooms200LinksPrev';
import type { GetChatRooms200LinksNext } from './getChatRooms200LinksNext';

export type GetChatRooms200Links = {
  first: GetChatRooms200LinksFirst;
  last: GetChatRooms200LinksLast;
  prev: GetChatRooms200LinksPrev;
  next: GetChatRooms200LinksNext;
};
