/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GeoDistrictResource } from './geoDistrictResource';

export type GetGeoDistricts200 = {
    data: GeoDistrictResource[];
};
