/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { GetMedias200MetaFrom } from './getMedias200MetaFrom';
import type { GetMedias200MetaLinksItem } from './getMedias200MetaLinksItem';
import type { GetMedias200MetaPath } from './getMedias200MetaPath';
import type { GetMedias200MetaTo } from './getMedias200MetaTo';

export type GetMedias200Meta = {
  /** @minimum 1 */
  current_page: number;
  /** @minimum 1 */
  from: GetMedias200MetaFrom;
  /** @minimum 1 */
  last_page: number;
  /** Generated paginator links. */
  links: GetMedias200MetaLinksItem[];
  /** Base path for paginator generated URLs. */
  path: GetMedias200MetaPath;
  /**
   * Number of items shown per page.
   * @minimum 0
   */
  per_page: number;
  /**
   * Number of the last item in the slice.
   * @minimum 1
   */
  to: GetMedias200MetaTo;
  /**
   * Total number of items being paginated.
   * @minimum 0
   */
  total: number;
};
