/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetMedias200LinksFirst } from './getMedias200LinksFirst';
import type { GetMedias200LinksLast } from './getMedias200LinksLast';
import type { GetMedias200LinksNext } from './getMedias200LinksNext';
import type { GetMedias200LinksPrev } from './getMedias200LinksPrev';

export type GetMedias200Links = {
    first: GetMedias200LinksFirst;
    last: GetMedias200LinksLast;
    prev: GetMedias200LinksPrev;
    next: GetMedias200LinksNext;
};
