/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetMedias200MetaLinksItemUrl } from './getMedias200MetaLinksItemUrl';

export type GetMedias200MetaLinksItem = {
  url: GetMedias200MetaLinksItemUrl;
  label: string;
  active: boolean;
};
