/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { MediaResource } from './mediaResource';
import type { GetMedias200Links } from './getMedias200Links';
import type { GetMedias200Meta } from './getMedias200Meta';

export type GetMedias200 = {
  data: MediaResource[];
  links: GetMedias200Links;
  meta: GetMedias200Meta;
};
