/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

/**
 * Base path for paginator generated URLs.
 */
export type GetMedias200MetaPath = string | null;
