/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetPayments200MetaLinksItemUrl } from './getPayments200MetaLinksItemUrl';

export type GetPayments200MetaLinksItem = {
  url: GetPayments200MetaLinksItemUrl;
  label: string;
  active: boolean;
};
