/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

export type GetPaymentsStatus = typeof GetPaymentsStatus[keyof typeof GetPaymentsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPaymentsStatus = {
  pending: 'pending',
  paid: 'paid',
  failed: 'failed',
} as const;
