/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

/**
 * Number of the last item in the slice.
 * @minimum 1
 */
export type GetPayments200MetaTo = number | null;
