/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { GetPayments200LinksFirst } from './getPayments200LinksFirst';
import type { GetPayments200LinksLast } from './getPayments200LinksLast';
import type { GetPayments200LinksPrev } from './getPayments200LinksPrev';
import type { GetPayments200LinksNext } from './getPayments200LinksNext';

export type GetPayments200Links = {
  first: GetPayments200LinksFirst;
  last: GetPayments200LinksLast;
  prev: GetPayments200LinksPrev;
  next: GetPayments200LinksNext;
};
