/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type GetPaymentsOwnerType = typeof GetPaymentsOwnerType[keyof typeof GetPaymentsOwnerType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPaymentsOwnerType = {
  user: 'user',
  company: 'company',
} as const;
