/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type GetPaymentsStatus =
    (typeof GetPaymentsStatus)[keyof typeof GetPaymentsStatus];

export const GetPaymentsStatus = {
    pending: 'pending',
    paid: 'paid',
    failed: 'failed',
} as const;
