/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetPayments200LinksFirst } from './getPayments200LinksFirst';
import type { GetPayments200LinksLast } from './getPayments200LinksLast';
import type { GetPayments200LinksNext } from './getPayments200LinksNext';
import type { GetPayments200LinksPrev } from './getPayments200LinksPrev';

export type GetPayments200Links = {
    first: GetPayments200LinksFirst;
    last: GetPayments200LinksLast;
    prev: GetPayments200LinksPrev;
    next: GetPayments200LinksNext;
};
