/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetPayments200Links } from './getPayments200Links';
import type { GetPayments200Meta } from './getPayments200Meta';
import type { PaymentResource } from './paymentResource';

export type GetPayments200 = {
    data: PaymentResource[];
    links: GetPayments200Links;
    meta: GetPayments200Meta;
};
