/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type GetTourCategoriesParams = {
company_id?: number | null;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number | null;
/**
 * @minimum 1
 */
page?: number | null;
sort_by?: 'name' | 'created_at' | 'updated_at' | null;
sort_order?: 'asc' | 'desc' | null;
};
