/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetTourCategories200LinksFirst } from './getTourCategories200LinksFirst';
import type { GetTourCategories200LinksLast } from './getTourCategories200LinksLast';
import type { GetTourCategories200LinksNext } from './getTourCategories200LinksNext';
import type { GetTourCategories200LinksPrev } from './getTourCategories200LinksPrev';

export type GetTourCategories200Links = {
    first: GetTourCategories200LinksFirst;
    last: GetTourCategories200LinksLast;
    prev: GetTourCategories200LinksPrev;
    next: GetTourCategories200LinksNext;
};
