/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { TourResource } from './tourResource';

export type GetTours200 = {
  data: TourResource[];
};
