/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type GetToursParams = {
/**
 * @maxLength 100
 */
search?: string | null;
category_id?: 'beach' | 'mountain' | 'cultural' | 'adventure' | 'wildlife' | 'historical' | 'religious' | 'culinary' | 'cruise' | 'safari' | null;
/**
 * @minimum 1
 * @maximum 365
 */
duration_min?: number | null;
/**
 * @minimum 1
 * @maximum 365
 */
duration_max?: number | null;
sort_by?: 'name' | 'duration_days' | 'created_at' | 'updated_at' | null;
sort_order?: 'asc' | 'desc' | null;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number | null;
/**
 * @minimum 1
 */
page?: number | null;
};
