/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type GetUsersParams = {
/**
 * @maxLength 100
 */
search?: string | null;
role?: string | null;
type?: string | null;
/**
 * @minimum 1
 */
page?: number | null;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number | null;
};
