/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetUsers200LinksFirst } from './getUsers200LinksFirst';
import type { GetUsers200LinksLast } from './getUsers200LinksLast';
import type { GetUsers200LinksPrev } from './getUsers200LinksPrev';
import type { GetUsers200LinksNext } from './getUsers200LinksNext';

export type GetUsers200Links = {
  first: GetUsers200LinksFirst;
  last: GetUsers200LinksLast;
  prev: GetUsers200LinksPrev;
  next: GetUsers200LinksNext;
};
