/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { UserResource } from './userResource';
import type { GetUsers200Links } from './getUsers200Links';
import type { GetUsers200Meta } from './getUsers200Meta';

export type GetUsers200 = {
  data: UserResource[];
  links: GetUsers200Links;
  meta: GetUsers200Meta;
};
