/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetUsers200Links } from './getUsers200Links';
import type { GetUsers200Meta } from './getUsers200Meta';
import type { UserResource } from './userResource';

export type GetUsers200 = {
    data: UserResource[];
    links: GetUsers200Links;
    meta: GetUsers200Meta;
};
