/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetUsers200LinksFirst } from './getUsers200LinksFirst';
import type { GetUsers200LinksLast } from './getUsers200LinksLast';
import type { GetUsers200LinksNext } from './getUsers200LinksNext';
import type { GetUsers200LinksPrev } from './getUsers200LinksPrev';

export type GetUsers200Links = {
    first: GetUsers200LinksFirst;
    last: GetUsers200LinksLast;
    prev: GetUsers200LinksPrev;
    next: GetUsers200LinksNext;
};
