/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetUsers200MetaLinksItemUrl } from './getUsers200MetaLinksItemUrl';

export type GetUsers200MetaLinksItem = {
  url: GetUsers200MetaLinksItemUrl;
  label: string;
  active: boolean;
};
