/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetVendors200LinksFirst } from './getVendors200LinksFirst';
import type { GetVendors200LinksLast } from './getVendors200LinksLast';
import type { GetVendors200LinksPrev } from './getVendors200LinksPrev';
import type { GetVendors200LinksNext } from './getVendors200LinksNext';

export type GetVendors200Links = {
  first: GetVendors200LinksFirst;
  last: GetVendors200LinksLast;
  prev: GetVendors200LinksPrev;
  next: GetVendors200LinksNext;
};
