/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetVendors200MetaLinksItemUrl } from './getVendors200MetaLinksItemUrl';

export type GetVendors200MetaLinksItem = {
  url: GetVendors200MetaLinksItemUrl;
  label: string;
  active: boolean;
};
