/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetWithdrawals200Links } from './getWithdrawals200Links';
import type { GetWithdrawals200Meta } from './getWithdrawals200Meta';
import type { WithdrawalResource } from './withdrawalResource';

export type GetWithdrawals200 = {
    data: WithdrawalResource[];
    links: GetWithdrawals200Links;
    meta: GetWithdrawals200Meta;
};
