/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type GetWithdrawalsOwnerType = typeof GetWithdrawalsOwnerType[keyof typeof GetWithdrawalsOwnerType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetWithdrawalsOwnerType = {
  user: 'user',
  company: 'company',
} as const;
