/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { GetWithdrawals200MetaLinksItemUrl } from './getWithdrawals200MetaLinksItemUrl';

export type GetWithdrawals200MetaLinksItem = {
  url: GetWithdrawals200MetaLinksItemUrl;
  label: string;
  active: boolean;
};
