/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetWithdrawals200LinksFirst } from './getWithdrawals200LinksFirst';
import type { GetWithdrawals200LinksLast } from './getWithdrawals200LinksLast';
import type { GetWithdrawals200LinksNext } from './getWithdrawals200LinksNext';
import type { GetWithdrawals200LinksPrev } from './getWithdrawals200LinksPrev';

export type GetWithdrawals200Links = {
    first: GetWithdrawals200LinksFirst;
    last: GetWithdrawals200LinksLast;
    prev: GetWithdrawals200LinksPrev;
    next: GetWithdrawals200LinksNext;
};
