/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetWallets200LinksFirst } from './getWallets200LinksFirst';
import type { GetWallets200LinksLast } from './getWallets200LinksLast';
import type { GetWallets200LinksNext } from './getWallets200LinksNext';
import type { GetWallets200LinksPrev } from './getWallets200LinksPrev';

export type GetWallets200Links = {
    first: GetWallets200LinksFirst;
    last: GetWallets200LinksLast;
    prev: GetWallets200LinksPrev;
    next: GetWallets200LinksNext;
};
