/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type GetWithdrawalsStatus =
    (typeof GetWithdrawalsStatus)[keyof typeof GetWithdrawalsStatus];

export const GetWithdrawalsStatus = {
    pending: 'pending',
    paid: 'paid',
    failed: 'failed',
} as const;
