/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetWallets200Links } from './getWallets200Links';
import type { GetWallets200Meta } from './getWallets200Meta';
import type { WalletResource } from './walletResource';

export type GetWallets200 = {
    data: WalletResource[];
    links: GetWallets200Links;
    meta: GetWallets200Meta;
};
