/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { GetWithdrawals200Links } from './getWithdrawals200Links';
import type { GetWithdrawals200Meta } from './getWithdrawals200Meta';
import type { WithdrawalResource } from './withdrawalResource';

export type GetWithdrawals200 = {
    data: WithdrawalResource[];
    links: GetWithdrawals200Links;
    meta: GetWithdrawals200Meta;
};
