/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { MediaCreatedAt } from './mediaCreatedAt';
import type { MediaData } from './mediaData';
import type { MediaDescription } from './mediaDescription';
import type { MediaType } from './mediaType';
import type { MediaUpdatedAt } from './mediaUpdatedAt';

export interface Media {
    id: number;
    name: string;
    description: MediaDescription;
    type: MediaType;
    subtype: string;
    data: MediaData;
    owner_type: string;
    owner_id: number;
    created_at: MediaCreatedAt;
    updated_at: MediaUpdatedAt;
}
