/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { MediasDestroy200Message } from './mediasDestroy200Message';

export type MediasDestroy200 = {
  message: MediasDestroy200Message;
};
