/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { MediaUpdateRequestDescription } from './mediaUpdateRequestDescription';

export interface MediaUpdateRequest {
  /** @maxLength 255 */
  name?: string;
  description?: MediaUpdateRequestDescription;
}
