/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

/**
 * kalau perlu user info
 */
export type MediaResourceUser = {
  id: number;
  name: string;
};
