/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { MediasUpdateBodyDescription } from './mediasUpdateBodyDescription';

export type MediasUpdateBody = {
  /** @maxLength 255 */
  name?: string;
  description?: MediasUpdateBodyDescription;
};
