/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { MediaResourceData } from './mediaResourceData';
import type { MediaResourceDescription } from './mediaResourceDescription';
import type { MediaResourceType } from './mediaResourceType';
import type { MediaResourceUser } from './mediaResourceUser';

export interface MediaResource {
    id: number;
    name: string;
    description: MediaResourceDescription;
    type: MediaResourceType;
    data: MediaResourceData;
    user_id: string;
    created_at: string;
    updated_at: string;
    /** kalau perlu user info */
    user?: MediaResourceUser;
}
