/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

export type MediasDestroy200Message = typeof MediasDestroy200Message[keyof typeof MediasDestroy200Message];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediasDestroy200Message = {
  Media_deleted: 'Media deleted',
} as const;
