/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type MediaType = (typeof MediaType)[keyof typeof MediaType];

export const MediaType = {
    image: 'image',
    document: 'document',
    raw: 'raw',
} as const;
