/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { MediaDescription } from './mediaDescription';
import type { MediaType } from './mediaType';
import type { MediaData } from './mediaData';
import type { MediaCreatedAt } from './mediaCreatedAt';
import type { MediaUpdatedAt } from './mediaUpdatedAt';

export interface Media {
  id: number;
  name: string;
  description: MediaDescription;
  type: MediaType;
  data: MediaData;
  user_id: number;
  created_at: MediaCreatedAt;
  updated_at: MediaUpdatedAt;
}
