/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type MediasDestroy200Message =
    (typeof MediasDestroy200Message)[keyof typeof MediasDestroy200Message];

export const MediasDestroy200Message = {
    Media_deleted: 'Media deleted',
} as const;
