/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { MediaResourceData } from './mediaResourceData';
import type { MediaResourceDescription } from './mediaResourceDescription';
import type { MediaResourceOwner } from './mediaResourceOwner';
import type { MediaResourceType } from './mediaResourceType';

export interface MediaResource {
    id: number;
    name: string;
    description: MediaResourceDescription;
    type: MediaResourceType;
    subtype: string;
    owner_type: string;
    owner_id: number;
    /** Image payloads use `files[]`; documents/raw use `url`, `size`, `media_type`. */
    data: MediaResourceData;
    created_at: string;
    updated_at: string;
    owner?: MediaResourceOwner;
}
