/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type OpenChatRequestSenderType = typeof OpenChatRequestSenderType[keyof typeof OpenChatRequestSenderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OpenChatRequestSenderType = {
  user: 'user',
  company: 'company',
} as const;
