/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type OpenChatRequestRecipientType = typeof OpenChatRequestRecipientType[keyof typeof OpenChatRequestRecipientType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OpenChatRequestRecipientType = {
  user: 'user',
  company: 'company',
} as const;
