/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { OpenChatRequestRecipientType } from './openChatRequestRecipientType';
import type { OpenChatRequestSenderType } from './openChatRequestSenderType';

export interface OpenChatRequest {
  recipient_type: OpenChatRequestRecipientType;
  recipient_id: number;
  sender_type: OpenChatRequestSenderType;
  sender_id: number;
}
