/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type PaymentMethodStatus =
    (typeof PaymentMethodStatus)[keyof typeof PaymentMethodStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethodStatus = {
    enabled: 'enabled',
    disabled: 'disabled',
    maintenance: 'maintenance',
} as const;
