/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentCreatedAt } from './paymentCreatedAt';
import type { PaymentExpiredAt } from './paymentExpiredAt';
import type { PaymentPaidAt } from './paymentPaidAt';
import type { PaymentPayload } from './paymentPayload';
import type { PaymentPaymentMethod } from './paymentPaymentMethod';
import type { PaymentStatus } from './paymentStatus';
import type { PaymentUpdatedAt } from './paymentUpdatedAt';

export interface Payment {
    id: number;
    owner_type: string;
    owner_id: number;
    payable_type: string;
    payable_id: number;
    provider: string;
    payment_method: PaymentPaymentMethod;
    amount: string;
    status: PaymentStatus;
    payload: PaymentPayload;
    expired_at: PaymentExpiredAt;
    paid_at: PaymentPaidAt;
    created_at: PaymentCreatedAt;
    updated_at: PaymentUpdatedAt;
}
