/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentPaymentMethod } from './paymentPaymentMethod';
import type { PaymentPayload } from './paymentPayload';
import type { PaymentPaidAt } from './paymentPaidAt';
import type { PaymentCreatedAt } from './paymentCreatedAt';
import type { PaymentUpdatedAt } from './paymentUpdatedAt';

export interface Payment {
  id: number;
  owner_type: string;
  owner_id: number;
  payable_type: string;
  payable_id: number;
  provider: string;
  payment_method: PaymentPaymentMethod;
  amount: string;
  status: string;
  payload: PaymentPayload;
  paid_at: PaymentPaidAt;
  created_at: PaymentCreatedAt;
  updated_at: PaymentUpdatedAt;
}
