/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */

export type PaymentMethodCategory =
    (typeof PaymentMethodCategory)[keyof typeof PaymentMethodCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethodCategory = {
    banktransfer: 'banktransfer',
    creditcard: 'creditcard',
    conveniencestore: 'conveniencestore',
    qris: 'qris',
} as const;
