/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentResourcePaymentMethod } from './paymentResourcePaymentMethod';
import type { PaymentResourcePayload } from './paymentResourcePayload';
import type { PaymentResourcePayable } from './paymentResourcePayable';

export interface PaymentResource {
  id: number;
  user_id: string;
  provider: string;
  payment_method: PaymentResourcePaymentMethod;
  amount: number;
  status: string;
  /** Important: include payload (contains snap_token, etc) */
  payload: PaymentResourcePayload;
  paid_at: string;
  created_at: string;
  updated_at: string;
  /** polymorphic relation */
  payable: PaymentResourcePayable;
}
