/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

/**
 * Important: include payload (contains snap_token, etc)
 */
export type PaymentResourcePayload = unknown[] | null;
