/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentMethodResourceCategory } from './paymentMethodResourceCategory';
import type { PaymentMethodResourceMeta } from './paymentMethodResourceMeta';
import type { PaymentMethodResourceStatus } from './paymentMethodResourceStatus';

export interface PaymentMethodResource {
    id: number;
    name: string;
    description: string;
    provider: string;
    method: string;
    category: PaymentMethodResourceCategory;
    meta: PaymentMethodResourceMeta;
    status: PaymentMethodResourceStatus;
    created_at: string;
    updated_at: string;
}
