/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type PaymentMethodCategory =
    (typeof PaymentMethodCategory)[keyof typeof PaymentMethodCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethodCategory = {
    banktransfer: 'banktransfer',
    creditcard: 'creditcard',
    conveniencestore: 'conveniencestore',
    qris: 'qris',
} as const;
