/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];

export const PaymentStatus = {
    unpaid: 'unpaid',
    pending: 'pending',
    paid: 'paid',
    failed: 'failed',
    expired: 'expired',
    refunded: 'refunded',
    cancelled: 'cancelled',
} as const;
