/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentMethodResourceCategory } from './paymentMethodResourceCategory';
import type { PaymentMethodResourceMeta } from './paymentMethodResourceMeta';
import type { PaymentMethodResourceStatus } from './paymentMethodResourceStatus';

export interface PaymentMethodResource {
    id: number;
    name: string;
    description: string;
    provider: string;
    method: string;
    category: PaymentMethodResourceCategory;
    meta: PaymentMethodResourceMeta;
    status: PaymentMethodResourceStatus;
    created_at: string;
    updated_at: string;
}
