/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentResourcePayable } from './paymentResourcePayable';
import type { PaymentResourcePayload } from './paymentResourcePayload';
import type { PaymentResourcePaymentMethod } from './paymentResourcePaymentMethod';
import type { PaymentStatus } from './paymentStatus';

export interface PaymentResource {
    id: number;
    user_id: string;
    provider: string;
    payment_method: PaymentResourcePaymentMethod;
    amount: number;
    status: PaymentStatus;
    /** Important: include payload (contains snap_token, etc) */
    payload: PaymentResourcePayload;
    paid_at: string;
    created_at: string;
    updated_at: string;
    /** polymorphic relation */
    payable: PaymentResourcePayable;
}
