/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export interface RegionResource {
  id: number;
  name: string;
  continent_id: number;
}
