/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { SearchResourceOwnersResourceAffiliates } from './searchResourceOwnersResourceAffiliates';
import type { SearchResourceOwnersResourceCompanies } from './searchResourceOwnersResourceCompanies';
import type { SearchResourceOwnersResourceUsers } from './searchResourceOwnersResourceUsers';

export interface SearchResourceOwnersResource {
    users: SearchResourceOwnersResourceUsers;
    companies: SearchResourceOwnersResourceCompanies;
    affiliates: SearchResourceOwnersResourceAffiliates;
}
