/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { SearchResourceOwnersResourceUsers } from './searchResourceOwnersResourceUsers';
import type { SearchResourceOwnersResourceCompanies } from './searchResourceOwnersResourceCompanies';
import type { SearchResourceOwnersResourceAffiliates } from './searchResourceOwnersResourceAffiliates';

export interface SearchResourceOwnersResource {
  users: SearchResourceOwnersResourceUsers;
  companies: SearchResourceOwnersResourceCompanies;
  affiliates: SearchResourceOwnersResourceAffiliates;
}
