/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { StoreChatMessageRequestUserId } from './storeChatMessageRequestUserId';
import type { StoreChatMessageRequestSenderType } from './storeChatMessageRequestSenderType';
import type { StoreChatMessageRequestSenderId } from './storeChatMessageRequestSenderId';
import type { StoreChatMessageRequestAttachment } from './storeChatMessageRequestAttachment';
import type { StoreChatMessageRequestAttachmentType } from './storeChatMessageRequestAttachmentType';

export interface StoreChatMessageRequest {
  user_id?: StoreChatMessageRequestUserId;
  /** @maxLength 50 */
  sender_type?: StoreChatMessageRequestSenderType;
  /** e.g., 'user', 'vendor', 'agent */
  sender_id?: StoreChatMessageRequestSenderId;
  /**
   * ID of the sender type
   * @maxLength 2000
   */
  message: string;
  /** @maxLength 2000 */
  attachment?: StoreChatMessageRequestAttachment;
  /**
   * max 10 MB
   * @maxLength 50
   */
  attachment_type?: StoreChatMessageRequestAttachmentType;
}
