/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type StoreMediaRequestType =
    (typeof StoreMediaRequestType)[keyof typeof StoreMediaRequestType];

export const StoreMediaRequestType = {
    image: 'image',
    document: 'document',
    raw: 'raw',
} as const;
