/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { StoreChatRoomRequestType } from './storeChatRoomRequestType';

export interface StoreChatRoomRequest {
  /** @maxLength 255 */
  name: string;
  type?: StoreChatRoomRequestType;
}
