/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { StoreMediaRequestName } from './storeMediaRequestName';
import type { StoreMediaRequestDescription } from './storeMediaRequestDescription';
import type { StoreMediaRequestType } from './storeMediaRequestType';

export interface StoreMediaRequest {
  /** @minimum 1 */
  owner_id: number;
  owner_type: string;
  /** @maxLength 255 */
  name?: StoreMediaRequestName;
  description?: StoreMediaRequestDescription;
  type: StoreMediaRequestType;
  data: Blob;
}
