/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

/**
 * max 10 MB
 * @maxLength 50
 */
export type StoreChatMessageRequestAttachmentType = string | null;
