/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { StoreChatMessageRequestAttachmentData } from './storeChatMessageRequestAttachmentData';
import type { StoreChatMessageRequestAttachmentType } from './storeChatMessageRequestAttachmentType';
import type { StoreChatMessageRequestSenderId } from './storeChatMessageRequestSenderId';
import type { StoreChatMessageRequestSenderType } from './storeChatMessageRequestSenderType';
import type { StoreChatMessageRequestUserId } from './storeChatMessageRequestUserId';

export interface StoreChatMessageRequest {
    user_id?: StoreChatMessageRequestUserId;
    /** @maxLength 50 */
    sender_type?: StoreChatMessageRequestSenderType;
    /** e.g., 'user', 'vendor', 'agent */
    sender_id?: StoreChatMessageRequestSenderId;
    /**
     * ID of the sender type
     * @maxLength 2000
     */
    message: string;
    /** @maxLength 2000 */
    attachment_data?: StoreChatMessageRequestAttachmentData;
    /**
     * max 10 MB
     * @maxLength 50
     */
    attachment_type?: StoreChatMessageRequestAttachmentType;
}
