/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { StoreChatMessageRequestAttachment } from './storeChatMessageRequestAttachment';
import type { StoreChatMessageRequestAttachmentType } from './storeChatMessageRequestAttachmentType';
import type { StoreChatMessageRequestReplyTo } from './storeChatMessageRequestReplyTo';

export interface StoreChatMessageRequest {
  /** @maxLength 2000 */
  message: string;
  /** @maxLength 2000 */
  attachment?: StoreChatMessageRequestAttachment;
  /**
   * max 10 MB
   * @maxLength 50
   */
  attachment_type?: StoreChatMessageRequestAttachmentType;
  /** e.g., image, video, file */
  reply_to?: StoreChatMessageRequestReplyTo;
}
