/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type StoreMediaRequestType = typeof StoreMediaRequestType[keyof typeof StoreMediaRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreMediaRequestType = {
  image: 'image',
  photo: 'photo',
  document: 'document',
} as const;
