/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { StoreMediaRequestDescription } from './storeMediaRequestDescription';
import type { StoreMediaRequestName } from './storeMediaRequestName';
import type { StoreMediaRequestType } from './storeMediaRequestType';

export interface StoreMediaRequest {
    /** @minimum 1 */
    owner_id: number;
    owner_type: string;
    /** @maxLength 255 */
    name?: StoreMediaRequestName;
    description?: StoreMediaRequestDescription;
    type: StoreMediaRequestType;
    /** @maxLength 50 */
    subtype: string;
    data: Blob;
}
