/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentResource } from './paymentResource';
import type { SyncPaymentStatus200Meta } from './syncPaymentStatus200Meta';

export type SyncPaymentStatus200 = {
    data: PaymentResource;
    meta: SyncPaymentStatus200Meta;
};
