/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { Company } from './company';
import type { Media } from './media';
import type { TourCategory } from './tourCategory';
import type { TourResourceCategoryId } from './tourResourceCategoryId';
import type { TourResourceContinentId } from './tourResourceContinentId';
import type { TourResourceContinentName } from './tourResourceContinentName';
import type { TourResourceCountryId } from './tourResourceCountryId';
import type { TourResourceCountryName } from './tourResourceCountryName';
import type { TourResourceCreatedAt } from './tourResourceCreatedAt';
import type { TourResourceDescription } from './tourResourceDescription';
import type { TourResourceDocumentId } from './tourResourceDocumentId';
import type { TourResourceImageId } from './tourResourceImageId';
import type { TourResourceProductCommissionCategoryId } from './tourResourceProductCommissionCategoryId';
import type { TourResourcePromoteNote } from './tourResourcePromoteNote';
import type { TourResourcePromoteTitle } from './tourResourcePromoteTitle';
import type { TourResourceRegionId } from './tourResourceRegionId';
import type { TourResourceRegionName } from './tourResourceRegionName';
import type { TourResourceUpdatedAt } from './tourResourceUpdatedAt';
import type { TourResourceUserId } from './tourResourceUserId';
import type { TourStatus } from './tourStatus';

export interface TourResource {
    id: number;
    code: string;
    name: string;
    description: TourResourceDescription;
    duration_days: number;
    status: TourStatus;
    destination: string;
    continent_name: TourResourceContinentName;
    region_name: TourResourceRegionName;
    country_name: TourResourceCountryName;
    showprice: string;
    earlybird: string;
    earlybird_note: string;
    currency: string;
    promoprice: string;
    promote_title: TourResourcePromoteTitle;
    promote_price: string;
    promote_note: TourResourcePromoteNote;
    company_id: number;
    category_id: TourResourceCategoryId;
    image_id: TourResourceImageId;
    document_id: TourResourceDocumentId;
    created_at: TourResourceCreatedAt;
    updated_at: TourResourceUpdatedAt;
    continent_id: TourResourceContinentId;
    region_id: TourResourceRegionId;
    country_id: TourResourceCountryId;
    user_id: TourResourceUserId;
    product_commission_category_id: TourResourceProductCommissionCategoryId;
    category?: TourCategory;
    image?: Media;
    document?: Media;
    company?: Company;
}
