/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type TourStatus = typeof TourStatus[keyof typeof TourStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TourStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
