/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { TourCategoryResourceCreatedAt } from './tourCategoryResourceCreatedAt';
import type { TourCategoryResourceDescription } from './tourCategoryResourceDescription';
import type { TourCategoryResourceUpdatedAt } from './tourCategoryResourceUpdatedAt';

export interface TourCategoryResource {
    id: number;
    name: string;
    description: TourCategoryResourceDescription;
    position_no: number;
    company_id: number;
    created_at: TourCategoryResourceCreatedAt;
    updated_at: TourCategoryResourceUpdatedAt;
}
