/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { TourCategoryDescription } from './tourCategoryDescription';
import type { TourCategoryCreatedAt } from './tourCategoryCreatedAt';
import type { TourCategoryUpdatedAt } from './tourCategoryUpdatedAt';

export interface TourCategory {
  id: number;
  name: string;
  description: TourCategoryDescription;
  user_id: number;
  created_at: TourCategoryCreatedAt;
  updated_at: TourCategoryUpdatedAt;
}
