/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { TourCategoryCreatedAt } from './tourCategoryCreatedAt';
import type { TourCategoryDescription } from './tourCategoryDescription';
import type { TourCategoryUpdatedAt } from './tourCategoryUpdatedAt';

export interface TourCategory {
    id: number;
    name: string;
    description: TourCategoryDescription;
    position_no: number;
    company_id: number;
    created_at: TourCategoryCreatedAt;
    updated_at: TourCategoryUpdatedAt;
}
