/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { TourCategoryResourceDescription } from './tourCategoryResourceDescription';
import type { TourCategoryResourceCreatedAt } from './tourCategoryResourceCreatedAt';
import type { TourCategoryResourceUpdatedAt } from './tourCategoryResourceUpdatedAt';

export interface TourCategoryResource {
  id: number;
  name: string;
  description: TourCategoryResourceDescription;
  user_id: number;
  created_at: TourCategoryResourceCreatedAt;
  updated_at: TourCategoryResourceUpdatedAt;
}
