/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateCompanySettingsRequestLandingPageData } from './updateCompanySettingsRequestLandingPageData';

export interface UpdateCompanySettingsRequest {
  enable_chatbot?: boolean;
  /** @maxLength 200000 */
  landing_page_data?: UpdateCompanySettingsRequestLandingPageData;
}
