/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type UpdateCountryBody = {
  continent_id?: number;
  region_id?: number;
  /** @maxLength 255 */
  country?: string;
};
