/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateContinentBodyUserId } from './updateContinentBodyUserId';

export type UpdateContinentBody = {
  /** @maxLength 255 */
  continent?: string;
  user_id?: UpdateContinentBodyUserId;
};
