/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateUserPreferenceRequestMetaPixelId } from './updateUserPreferenceRequestMetaPixelId';
import type { UpdateUserPreferenceRequestUseChatbot } from './updateUserPreferenceRequestUseChatbot';
import type { UpdateUserPreferenceRequestLandingPageTemplateId } from './updateUserPreferenceRequestLandingPageTemplateId';
import type { UpdateUserPreferenceRequestLandingPageTemplateData } from './updateUserPreferenceRequestLandingPageTemplateData';

export interface UpdateUserPreferenceRequest {
  /** @maxLength 100 */
  meta_pixel_id?: UpdateUserPreferenceRequestMetaPixelId;
  use_chatbot?: UpdateUserPreferenceRequestUseChatbot;
  landing_page_template_id?: UpdateUserPreferenceRequestLandingPageTemplateId;
  landing_page_template_data?: UpdateUserPreferenceRequestLandingPageTemplateData;
}
