/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

/**
 * @maxLength 2000
 */
export type UpdateChatMessageRequestAttachment = string | null;
