/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateChatMessageRequestAttachmentData } from './updateChatMessageRequestAttachmentData';
import type { UpdateChatMessageRequestAttachmentType } from './updateChatMessageRequestAttachmentType';

export interface UpdateChatMessageRequest {
  /** @maxLength 2000 */
  message?: string;
  /** @maxLength 2000 */
  attachment_data?: UpdateChatMessageRequestAttachmentData;
  /** @maxLength 50 */
  attachment_type?: UpdateChatMessageRequestAttachmentType;
}
