/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

/**
 * @maxLength 100
 */
export type UpdateUserPreferenceRequestMetaPixelId = string | null;
