/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateChatRoomRequestType } from './updateChatRoomRequestType';

export interface UpdateChatRoomRequest {
  /** @maxLength 255 */
  name?: string;
  /** allow partial updates */
  type?: UpdateChatRoomRequestType;
}
