/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */

/**
 * allow partial updates
 */
export type UpdateChatRoomRequestType = 'group' | 'private' | null;
