/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { UserPreferenceResource } from './userPreferenceResource';

export type UserPreferenceUpdate200 = {
  data: UserPreferenceResource;
};
