/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { UserResourceEmailVerifiedAt } from './userResourceEmailVerifiedAt';
import type { UserResourcePhotoId } from './userResourcePhotoId';
import type { UserResourceCreatedAt } from './userResourceCreatedAt';
import type { UserResourceUpdatedAt } from './userResourceUpdatedAt';
import type { UserResourceTwoFactorConfirmedAt } from './userResourceTwoFactorConfirmedAt';

export interface UserResource {
  id: number;
  name: string;
  email: string;
  email_verified_at: UserResourceEmailVerifiedAt;
  username: string;
  address: string;
  phone: string;
  type: string;
  photo_id: UserResourcePhotoId;
  created_at: UserResourceCreatedAt;
  updated_at: UserResourceUpdatedAt;
  two_factor_confirmed_at: UserResourceTwoFactorConfirmedAt;
  photo_url: string;
}
