/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { UserPreferenceResourceUpdatedAt } from './userPreferenceResourceUpdatedAt';

export interface UserPreferenceResource {
  id: number;
  meta_pixel_id: string;
  use_chatbot: number;
  landing_page_template_id: string;
  landing_page_template_data: string;
  updated_at: UserPreferenceResourceUpdatedAt;
}
