/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export interface UserResource {
  id: number;
  name: string;
  username: string;
  email: string;
  phone: string;
  address: string;
  type: string;
  photo_url: string;
  roles?: unknown[];
  permissions?: unknown[];
  created_at: string;
}
