/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { UserEmailVerifiedAt } from './userEmailVerifiedAt';
import type { UserPhotoId } from './userPhotoId';
import type { UserCreatedAt } from './userCreatedAt';
import type { UserUpdatedAt } from './userUpdatedAt';
import type { UserTwoFactorConfirmedAt } from './userTwoFactorConfirmedAt';

export interface User {
  id: number;
  name: string;
  email: string;
  email_verified_at: UserEmailVerifiedAt;
  username: string;
  address: string;
  phone: string;
  type: string;
  photo_id: UserPhotoId;
  created_at: UserCreatedAt;
  updated_at: UserUpdatedAt;
  two_factor_confirmed_at: UserTwoFactorConfirmedAt;
  photo_url: string;
}
