/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { UserEmailVerifiedAt } from './userEmailVerifiedAt';
import type { UserCreatedAt } from './userCreatedAt';
import type { UserUpdatedAt } from './userUpdatedAt';
import type { UserTwoFactorConfirmedAt } from './userTwoFactorConfirmedAt';
import type { UserPhotoId } from './userPhotoId';
import type { UserActivedDate } from './userActivedDate';
import type { UserLogoImage } from './userLogoImage';

export interface User {
  id: number;
  name: string;
  email: string;
  email_verified_at: UserEmailVerifiedAt;
  username: string;
  address: string;
  phone: string;
  type: string;
  created_at: UserCreatedAt;
  updated_at: UserUpdatedAt;
  two_factor_confirmed_at: UserTwoFactorConfirmedAt;
  photo_id: UserPhotoId;
  active: string;
  actived_date: UserActivedDate;
  logo_image: UserLogoImage;
  catalog_link: string;
  photo_url: string;
}
