/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export interface UserPreferenceResource {
  id: string;
  meta_pixel_id: string;
  use_chatbot: string;
  landing_page_template_data: string;
  updated_at: string;
}
