/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

/**
 * A detailed description of each field that failed validation.
 */
export type ValidationExceptionResponseErrors = {[key: string]: string[]};
