/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { VendorRememberToken } from './vendorRememberToken';
import type { VendorCreatedAt } from './vendorCreatedAt';
import type { VendorUpdatedAt } from './vendorUpdatedAt';

export interface Vendor {
  id: number;
  name: string;
  username: string;
  email: string;
  address: string;
  phone: string;
  remember_token: VendorRememberToken;
  created_at: VendorCreatedAt;
  updated_at: VendorUpdatedAt;
}
