/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { WalletResourceCurrency } from './walletResourceCurrency';
import type { WalletResourceDescription } from './walletResourceDescription';
import type { WalletResourceHolder } from './walletResourceHolder';
import type { WalletResourceLinks } from './walletResourceLinks';
import type { WalletResourceStatus } from './walletResourceStatus';
import type { WalletResourceTotalWithdrawals } from './walletResourceTotalWithdrawals';
import type { WalletResourceTransactionCount } from './walletResourceTransactionCount';
import type { WalletResourceType } from './walletResourceType';

export interface WalletResource {
    id: number;
    uuid: string;
    holder?: WalletResourceHolder;
    holder_id: number;
    holder_type: string;
    name: string;
    slug: string;
    description: WalletResourceDescription;
    balance: string;
    balance_int: string;
    balance_formatted: string;
    meta: unknown[];
    currency: WalletResourceCurrency;
    status: WalletResourceStatus;
    type: WalletResourceType;
    total_deposits: unknown;
    total_withdrawals?: WalletResourceTotalWithdrawals;
    transaction_count: WalletResourceTransactionCount;
    /** Dates */
    created_at: string;
    updated_at: string;
    last_transaction_at?: string;
    /** Links */
    links: WalletResourceLinks;
}
