/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { WalletsIndex200MetaLinksItemUrl } from './walletsIndex200MetaLinksItemUrl';

export type WalletsIndex200MetaLinksItem = {
  url: WalletsIndex200MetaLinksItemUrl;
  label: string;
  active: boolean;
};
