/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { WalletResource } from './walletResource';
import type { WalletsIndex200Links } from './walletsIndex200Links';
import type { WalletsIndex200Meta } from './walletsIndex200Meta';

export type WalletsIndex200 = {
  data: WalletResource[];
  links: WalletsIndex200Links;
  meta: WalletsIndex200Meta;
};
