/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { WalletsIndex200LinksFirst } from './walletsIndex200LinksFirst';
import type { WalletsIndex200LinksLast } from './walletsIndex200LinksLast';
import type { WalletsIndex200LinksPrev } from './walletsIndex200LinksPrev';
import type { WalletsIndex200LinksNext } from './walletsIndex200LinksNext';

export type WalletsIndex200Links = {
  first: WalletsIndex200LinksFirst;
  last: WalletsIndex200LinksLast;
  prev: WalletsIndex200LinksPrev;
  next: WalletsIndex200LinksNext;
};
