/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { WalletResourceHolderType } from './walletResourceHolderType';

export type WalletResourceHolder = {
  id: string;
  name: string;
  email: string;
  type: WalletResourceHolderType;
};
