/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import type { WalletResourceHolder } from './walletResourceHolder';
import type { WalletResourceMeta } from './walletResourceMeta';
import type { WalletResourceCurrency } from './walletResourceCurrency';
import type { WalletResourceStatus } from './walletResourceStatus';
import type { WalletResourceType } from './walletResourceType';
import type { WalletResourceTotalWithdrawals } from './walletResourceTotalWithdrawals';
import type { WalletResourceTransactionCount } from './walletResourceTransactionCount';
import type { WalletResourceLinks } from './walletResourceLinks';

export interface WalletResource {
  id: string;
  uuid: string;
  holder?: WalletResourceHolder;
  holder_id: string;
  holder_type: string;
  name: string;
  slug: string;
  description: string;
  balance: string;
  balance_int: string;
  balance_formatted: string;
  meta: WalletResourceMeta;
  currency: WalletResourceCurrency;
  status: WalletResourceStatus;
  type: WalletResourceType;
  /** Statistics */
  total_deposits?: string;
  total_withdrawals?: WalletResourceTotalWithdrawals;
  transaction_count: WalletResourceTransactionCount;
  /** Dates */
  created_at: string;
  updated_at: string;
  last_transaction_at?: string;
  /** Links */
  links: WalletResourceLinks;
}
