/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type { WalletResourceHolderType } from './walletResourceHolderType';

export type WalletResourceHolder = {
    id: number;
    name: string;
    email: string;
    type: WalletResourceHolderType;
};
