/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

/**
 * Links
 */
export type WalletResourceLinks = {
    self: string;
    transactions: string;
    balance: string;
};
