/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type { WithdrawalResourceCreatedAt } from './withdrawalResourceCreatedAt';
import type { WithdrawalResourceNote } from './withdrawalResourceNote';
import type { WithdrawalResourcePaidAt } from './withdrawalResourcePaidAt';
import type { WithdrawalResourceWalletId } from './withdrawalResourceWalletId';
import type { WithdrawalStatus } from './withdrawalStatus';

export interface WithdrawalResource {
    id: number;
    user_id: string;
    bank_account_id: number;
    wallet_id: WithdrawalResourceWalletId;
    amount: number;
    status: WithdrawalStatus;
    note: WithdrawalResourceNote;
    approved_at: string;
    processed_at: string;
    paid_at: WithdrawalResourcePaidAt;
    created_at: WithdrawalResourceCreatedAt;
}
