/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */

export type WithdrawalStatus =
    (typeof WithdrawalStatus)[keyof typeof WithdrawalStatus];

export const WithdrawalStatus = {
    pending: 'pending',
    processing: 'processing',
    rejected: 'rejected',
    cancelled: 'cancelled',
    paid: 'paid',
} as const;
