/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
    GetPaymentMethods200,
    GetPaymentMethodsParams,
    ValidationExceptionResponse,
} from '.././model';

import { apiInstance } from '.././api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List available payment methods
 */
export const getPaymentMethods = (
    params?: GetPaymentMethodsParams,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<GetPaymentMethods200>(
        { url: `/payment-methods`, method: 'GET', params, signal },
        options,
    );
};

export const getGetPaymentMethodsQueryKey = (
    params?: GetPaymentMethodsParams,
) => {
    return [`/payment-methods`, ...(params ? [params] : [])] as const;
};

export const getGetPaymentMethodsQueryOptions = <
    TData = Awaited<ReturnType<typeof getPaymentMethods>>,
    TError = ValidationExceptionResponse,
>(
    params?: GetPaymentMethodsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPaymentMethods>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetPaymentMethodsQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getPaymentMethods>>
    > = ({ signal }) => getPaymentMethods(params, requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getPaymentMethods>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPaymentMethodsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getPaymentMethods>>
>;
export type GetPaymentMethodsQueryError = ValidationExceptionResponse;

export function useGetPaymentMethods<
    TData = Awaited<ReturnType<typeof getPaymentMethods>>,
    TError = ValidationExceptionResponse,
>(
    params: undefined | GetPaymentMethodsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPaymentMethods>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getPaymentMethods>>,
                    TError,
                    Awaited<ReturnType<typeof getPaymentMethods>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPaymentMethods<
    TData = Awaited<ReturnType<typeof getPaymentMethods>>,
    TError = ValidationExceptionResponse,
>(
    params?: GetPaymentMethodsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPaymentMethods>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getPaymentMethods>>,
                    TError,
                    Awaited<ReturnType<typeof getPaymentMethods>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPaymentMethods<
    TData = Awaited<ReturnType<typeof getPaymentMethods>>,
    TError = ValidationExceptionResponse,
>(
    params?: GetPaymentMethodsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPaymentMethods>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List available payment methods
 */

export function useGetPaymentMethods<
    TData = Awaited<ReturnType<typeof getPaymentMethods>>,
    TError = ValidationExceptionResponse,
>(
    params?: GetPaymentMethodsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPaymentMethods>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetPaymentMethodsQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}
