/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
    AdminSearchCompanies200,
    AdminSearchCompaniesParams,
    AdminSearchResourceOwners200,
    AdminSearchResourceOwnersParams,
    AuthenticationExceptionResponse,
    ValidationExceptionResponse,
} from '.././model';

import { apiInstance } from '.././api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Display a listing of the users
 */
export const adminSearchCompanies = (
    params?: AdminSearchCompaniesParams,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<AdminSearchCompanies200>(
        { url: `/admin/misc/search-companies`, method: 'GET', params, signal },
        options,
    );
};

export const getAdminSearchCompaniesQueryKey = (
    params?: AdminSearchCompaniesParams,
) => {
    return [
        `/admin/misc/search-companies`,
        ...(params ? [params] : []),
    ] as const;
};

export const getAdminSearchCompaniesQueryOptions = <
    TData = Awaited<ReturnType<typeof adminSearchCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: AdminSearchCompaniesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchCompanies>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getAdminSearchCompaniesQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminSearchCompanies>>
    > = ({ signal }) => adminSearchCompanies(params, requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminSearchCompanies>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminSearchCompaniesQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminSearchCompanies>>
>;
export type AdminSearchCompaniesQueryError =
    | AuthenticationExceptionResponse
    | ValidationExceptionResponse;

export function useAdminSearchCompanies<
    TData = Awaited<ReturnType<typeof adminSearchCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params: undefined | AdminSearchCompaniesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchCompanies>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminSearchCompanies>>,
                    TError,
                    Awaited<ReturnType<typeof adminSearchCompanies>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminSearchCompanies<
    TData = Awaited<ReturnType<typeof adminSearchCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: AdminSearchCompaniesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchCompanies>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminSearchCompanies>>,
                    TError,
                    Awaited<ReturnType<typeof adminSearchCompanies>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminSearchCompanies<
    TData = Awaited<ReturnType<typeof adminSearchCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: AdminSearchCompaniesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchCompanies>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Display a listing of the users
 */

export function useAdminSearchCompanies<
    TData = Awaited<ReturnType<typeof adminSearchCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: AdminSearchCompaniesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchCompanies>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getAdminSearchCompaniesQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Display a listing of resource owners
 */
export const adminSearchResourceOwners = (
    params?: AdminSearchResourceOwnersParams,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<AdminSearchResourceOwners200>(
        {
            url: `/admin/misc/search-resource-owners`,
            method: 'GET',
            params,
            signal,
        },
        options,
    );
};

export const getAdminSearchResourceOwnersQueryKey = (
    params?: AdminSearchResourceOwnersParams,
) => {
    return [
        `/admin/misc/search-resource-owners`,
        ...(params ? [params] : []),
    ] as const;
};

export const getAdminSearchResourceOwnersQueryOptions = <
    TData = Awaited<ReturnType<typeof adminSearchResourceOwners>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: AdminSearchResourceOwnersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchResourceOwners>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getAdminSearchResourceOwnersQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminSearchResourceOwners>>
    > = ({ signal }) =>
        adminSearchResourceOwners(params, requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminSearchResourceOwners>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminSearchResourceOwnersQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminSearchResourceOwners>>
>;
export type AdminSearchResourceOwnersQueryError =
    | AuthenticationExceptionResponse
    | ValidationExceptionResponse;

export function useAdminSearchResourceOwners<
    TData = Awaited<ReturnType<typeof adminSearchResourceOwners>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params: undefined | AdminSearchResourceOwnersParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchResourceOwners>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminSearchResourceOwners>>,
                    TError,
                    Awaited<ReturnType<typeof adminSearchResourceOwners>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminSearchResourceOwners<
    TData = Awaited<ReturnType<typeof adminSearchResourceOwners>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: AdminSearchResourceOwnersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchResourceOwners>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminSearchResourceOwners>>,
                    TError,
                    Awaited<ReturnType<typeof adminSearchResourceOwners>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminSearchResourceOwners<
    TData = Awaited<ReturnType<typeof adminSearchResourceOwners>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: AdminSearchResourceOwnersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchResourceOwners>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Display a listing of resource owners
 */

export function useAdminSearchResourceOwners<
    TData = Awaited<ReturnType<typeof adminSearchResourceOwners>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: AdminSearchResourceOwnersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminSearchResourceOwners>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getAdminSearchResourceOwnersQueryOptions(
        params,
        options,
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}
