/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  CompanySettings,
  CompanyUpdateSettings200,
  GetCompanies200,
  GetCompaniesParams,
  ModelNotFoundExceptionResponse,
  UpdateCompanySettingsRequest,
  ValidationExceptionResponse
} from '.././model';

import { apiInstance } from '.././api-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Display a listing of the users
 */
export const getCompanies = (
    params?: GetCompaniesParams,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetCompanies200>(
      {url: `/companies`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCompaniesQueryKey = (params?: GetCompaniesParams,) => {
    return [
    `/companies`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCompaniesQueryOptions = <TData = Awaited<ReturnType<typeof getCompanies>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(params?: GetCompaniesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompaniesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompanies>>> = ({ signal }) => getCompanies(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompaniesQueryResult = NonNullable<Awaited<ReturnType<typeof getCompanies>>>
export type GetCompaniesQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse


export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  GetCompaniesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanies>>,
          TError,
          Awaited<ReturnType<typeof getCompanies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params?: GetCompaniesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanies>>,
          TError,
          Awaited<ReturnType<typeof getCompanies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params?: GetCompaniesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a listing of the users
 */

export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params?: GetCompaniesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompaniesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const companyShowSettings = (
    company: number,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<CompanySettings>(
      {url: `/companies/${company}/settings`, method: 'GET', signal
    },
      options);
    }
  



export const getCompanyShowSettingsQueryKey = (company?: number,) => {
    return [
    `/companies/${company}/settings`
    ] as const;
    }

    
export const getCompanyShowSettingsQueryOptions = <TData = Awaited<ReturnType<typeof companyShowSettings>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(company: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyShowSettings>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompanyShowSettingsQueryKey(company);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof companyShowSettings>>> = ({ signal }) => companyShowSettings(company, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(company), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof companyShowSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompanyShowSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof companyShowSettings>>>
export type CompanyShowSettingsQueryError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse


export function useCompanyShowSettings<TData = Awaited<ReturnType<typeof companyShowSettings>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 company: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyShowSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyShowSettings>>,
          TError,
          Awaited<ReturnType<typeof companyShowSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyShowSettings<TData = Awaited<ReturnType<typeof companyShowSettings>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 company: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyShowSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyShowSettings>>,
          TError,
          Awaited<ReturnType<typeof companyShowSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyShowSettings<TData = Awaited<ReturnType<typeof companyShowSettings>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 company: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyShowSettings>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCompanyShowSettings<TData = Awaited<ReturnType<typeof companyShowSettings>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 company: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyShowSettings>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompanyShowSettingsQueryOptions(company,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const companyUpdateSettings = (
    company: number,
    updateCompanySettingsRequest: UpdateCompanySettingsRequest,
 options?: SecondParameter<typeof apiInstance>,) => {
      
      
      return apiInstance<CompanyUpdateSettings200>(
      {url: `/companies/${company}/settings`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCompanySettingsRequest
    },
      options);
    }
  


export const getCompanyUpdateSettingsMutationOptions = <TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companyUpdateSettings>>, TError,{company: number;data: UpdateCompanySettingsRequest}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof companyUpdateSettings>>, TError,{company: number;data: UpdateCompanySettingsRequest}, TContext> => {

const mutationKey = ['companyUpdateSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof companyUpdateSettings>>, {company: number;data: UpdateCompanySettingsRequest}> = (props) => {
          const {company,data} = props ?? {};

          return  companyUpdateSettings(company,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CompanyUpdateSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof companyUpdateSettings>>>
    export type CompanyUpdateSettingsMutationBody = UpdateCompanySettingsRequest
    export type CompanyUpdateSettingsMutationError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse

    export const useCompanyUpdateSettings = <TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companyUpdateSettings>>, TError,{company: number;data: UpdateCompanySettingsRequest}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof companyUpdateSettings>>,
        TError,
        {company: number;data: UpdateCompanySettingsRequest},
        TContext
      > => {

      const mutationOptions = getCompanyUpdateSettingsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    