/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type {
    AuthenticationExceptionResponse,
    GetCompanies200,
    GetCompaniesParams,
    GetCompanySettings200,
    ModelNotFoundExceptionResponse,
    UpdateCompanySettings200,
    UpdateCompanySettingsRequest,
    ValidationExceptionResponse,
} from '.././model';

import { apiInstance } from '.././api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List companies with optional filters
 */
export const getCompanies = (
    params?: GetCompaniesParams,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<GetCompanies200>(
        { url: `/companies`, method: 'GET', params, signal },
        options,
    );
};

export const getGetCompaniesQueryKey = (params?: GetCompaniesParams) => {
    return [`/companies`, ...(params ? [params] : [])] as const;
};

export const getGetCompaniesQueryOptions = <
    TData = Awaited<ReturnType<typeof getCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: GetCompaniesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanies>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCompaniesQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompanies>>> = ({
        signal,
    }) => getCompanies(params, requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getCompanies>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCompaniesQueryResult = NonNullable<
    Awaited<ReturnType<typeof getCompanies>>
>;
export type GetCompaniesQueryError =
    | AuthenticationExceptionResponse
    | ValidationExceptionResponse;

export function useGetCompanies<
    TData = Awaited<ReturnType<typeof getCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params: undefined | GetCompaniesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanies>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCompanies>>,
                    TError,
                    Awaited<ReturnType<typeof getCompanies>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCompanies<
    TData = Awaited<ReturnType<typeof getCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: GetCompaniesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanies>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCompanies>>,
                    TError,
                    Awaited<ReturnType<typeof getCompanies>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCompanies<
    TData = Awaited<ReturnType<typeof getCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: GetCompaniesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanies>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List companies with optional filters
 */

export function useGetCompanies<
    TData = Awaited<ReturnType<typeof getCompanies>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: GetCompaniesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanies>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetCompaniesQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Get company dashboard settings
 */
export const getCompanySettings = (
    company: number,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<GetCompanySettings200>(
        { url: `/companies/${company}/settings`, method: 'GET', signal },
        options,
    );
};

export const getGetCompanySettingsQueryKey = (company?: number) => {
    return [`/companies/${company}/settings`] as const;
};

export const getGetCompanySettingsQueryOptions = <
    TData = Awaited<ReturnType<typeof getCompanySettings>>,
    TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse,
>(
    company: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanySettings>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetCompanySettingsQueryKey(company);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getCompanySettings>>
    > = ({ signal }) => getCompanySettings(company, requestOptions, signal);

    return {
        queryKey,
        queryFn,
        enabled: !!company,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getCompanySettings>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCompanySettingsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getCompanySettings>>
>;
export type GetCompanySettingsQueryError =
    | AuthenticationExceptionResponse
    | ModelNotFoundExceptionResponse;

export function useGetCompanySettings<
    TData = Awaited<ReturnType<typeof getCompanySettings>>,
    TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse,
>(
    company: number,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanySettings>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCompanySettings>>,
                    TError,
                    Awaited<ReturnType<typeof getCompanySettings>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCompanySettings<
    TData = Awaited<ReturnType<typeof getCompanySettings>>,
    TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse,
>(
    company: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanySettings>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCompanySettings>>,
                    TError,
                    Awaited<ReturnType<typeof getCompanySettings>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCompanySettings<
    TData = Awaited<ReturnType<typeof getCompanySettings>>,
    TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse,
>(
    company: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanySettings>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get company dashboard settings
 */

export function useGetCompanySettings<
    TData = Awaited<ReturnType<typeof getCompanySettings>>,
    TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse,
>(
    company: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCompanySettings>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetCompanySettingsQueryOptions(company, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Update company dashboard settings
 */
export const updateCompanySettings = (
    company: number,
    updateCompanySettingsRequest: UpdateCompanySettingsRequest,
    options?: SecondParameter<typeof apiInstance>,
) => {
    return apiInstance<UpdateCompanySettings200>(
        {
            url: `/companies/${company}/settings`,
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            data: updateCompanySettingsRequest,
        },
        options,
    );
};

export const getUpdateCompanySettingsMutationOptions = <
    TError =
        | AuthenticationExceptionResponse
        | ModelNotFoundExceptionResponse
        | ValidationExceptionResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateCompanySettings>>,
        TError,
        { company: number; data: UpdateCompanySettingsRequest },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateCompanySettings>>,
    TError,
    { company: number; data: UpdateCompanySettingsRequest },
    TContext
> => {
    const mutationKey = ['updateCompanySettings'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateCompanySettings>>,
        { company: number; data: UpdateCompanySettingsRequest }
    > = (props) => {
        const { company, data } = props ?? {};

        return updateCompanySettings(company, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateCompanySettingsMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateCompanySettings>>
>;
export type UpdateCompanySettingsMutationBody = UpdateCompanySettingsRequest;
export type UpdateCompanySettingsMutationError =
    | AuthenticationExceptionResponse
    | ModelNotFoundExceptionResponse
    | ValidationExceptionResponse;

/**
 * @summary Update company dashboard settings
 */
export const useUpdateCompanySettings = <
    TError =
        | AuthenticationExceptionResponse
        | ModelNotFoundExceptionResponse
        | ValidationExceptionResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateCompanySettings>>,
            TError,
            { company: number; data: UpdateCompanySettingsRequest },
            TContext
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof updateCompanySettings>>,
    TError,
    { company: number; data: UpdateCompanySettingsRequest },
    TContext
> => {
    const mutationOptions = getUpdateCompanySettingsMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
