/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  GetWithdrawals200,
  GetWithdrawalsParams,
  ValidationExceptionResponse
} from '.././model';

import { apiInstance } from '.././api-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary get payment list
 */
export const getWithdrawals = (
    params?: GetWithdrawalsParams,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetWithdrawals200>(
      {url: `/withdrawals`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetWithdrawalsQueryKey = (params?: GetWithdrawalsParams,) => {
    return [
    `/withdrawals`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetWithdrawalsQueryOptions = <TData = Awaited<ReturnType<typeof getWithdrawals>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(params?: GetWithdrawalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWithdrawalsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWithdrawals>>> = ({ signal }) => getWithdrawals(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWithdrawals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWithdrawalsQueryResult = NonNullable<Awaited<ReturnType<typeof getWithdrawals>>>
export type GetWithdrawalsQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse


export function useGetWithdrawals<TData = Awaited<ReturnType<typeof getWithdrawals>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  GetWithdrawalsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWithdrawals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWithdrawals>>,
          TError,
          Awaited<ReturnType<typeof getWithdrawals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWithdrawals<TData = Awaited<ReturnType<typeof getWithdrawals>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params?: GetWithdrawalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWithdrawals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWithdrawals>>,
          TError,
          Awaited<ReturnType<typeof getWithdrawals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWithdrawals<TData = Awaited<ReturnType<typeof getWithdrawals>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params?: GetWithdrawalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary get payment list
 */

export function useGetWithdrawals<TData = Awaited<ReturnType<typeof getWithdrawals>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params?: GetWithdrawalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWithdrawalsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




