/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  WalletsIndex200,
  WalletsIndexParams
} from '.././model';

import { apiInstance } from '.././api-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const walletsIndex = (
    params?: WalletsIndexParams,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<WalletsIndex200>(
      {url: `/wallets`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getWalletsIndexQueryKey = (params?: WalletsIndexParams,) => {
    return [
    `/wallets`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getWalletsIndexQueryOptions = <TData = Awaited<ReturnType<typeof walletsIndex>>, TError = AuthenticationExceptionResponse>(params?: WalletsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof walletsIndex>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWalletsIndexQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof walletsIndex>>> = ({ signal }) => walletsIndex(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof walletsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WalletsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof walletsIndex>>>
export type WalletsIndexQueryError = AuthenticationExceptionResponse


export function useWalletsIndex<TData = Awaited<ReturnType<typeof walletsIndex>>, TError = AuthenticationExceptionResponse>(
 params: undefined |  WalletsIndexParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof walletsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletsIndex>>,
          TError,
          Awaited<ReturnType<typeof walletsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWalletsIndex<TData = Awaited<ReturnType<typeof walletsIndex>>, TError = AuthenticationExceptionResponse>(
 params?: WalletsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof walletsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletsIndex>>,
          TError,
          Awaited<ReturnType<typeof walletsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWalletsIndex<TData = Awaited<ReturnType<typeof walletsIndex>>, TError = AuthenticationExceptionResponse>(
 params?: WalletsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof walletsIndex>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWalletsIndex<TData = Awaited<ReturnType<typeof walletsIndex>>, TError = AuthenticationExceptionResponse>(
 params?: WalletsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof walletsIndex>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWalletsIndexQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




