/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  CreateRegion201,
  CreateRegionBody,
  GetRegionById200,
  GetRegions200,
  GetRegionsParams,
  UpdateRegion200,
  UpdateRegionBody,
  ValidationExceptionResponse
} from '.././model';

import { apiInstance } from '.././api-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Store a newly created resource in storage
 */
export const createRegion = (
    createRegionBody: CreateRegionBody,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<CreateRegion201>(
      {url: `/regions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRegionBody, signal
    },
      options);
    }
  


export const getCreateRegionMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRegion>>, TError,{data: CreateRegionBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createRegion>>, TError,{data: CreateRegionBody}, TContext> => {

const mutationKey = ['createRegion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRegion>>, {data: CreateRegionBody}> = (props) => {
          const {data} = props ?? {};

          return  createRegion(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRegionMutationResult = NonNullable<Awaited<ReturnType<typeof createRegion>>>
    export type CreateRegionMutationBody = CreateRegionBody
    export type CreateRegionMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Store a newly created resource in storage
 */
export const useCreateRegion = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRegion>>, TError,{data: CreateRegionBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRegion>>,
        TError,
        {data: CreateRegionBody},
        TContext
      > => {

      const mutationOptions = getCreateRegionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Display a listing of the resource
 */
export const getRegions = (
    params?: GetRegionsParams,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetRegions200>(
      {url: `/regions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetRegionsQueryKey = (params?: GetRegionsParams,) => {
    return [
    `/regions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRegionsQueryOptions = <TData = Awaited<ReturnType<typeof getRegions>>, TError = ValidationExceptionResponse>(params?: GetRegionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegions>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRegionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRegions>>> = ({ signal }) => getRegions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRegions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRegionsQueryResult = NonNullable<Awaited<ReturnType<typeof getRegions>>>
export type GetRegionsQueryError = ValidationExceptionResponse


export function useGetRegions<TData = Awaited<ReturnType<typeof getRegions>>, TError = ValidationExceptionResponse>(
 params: undefined |  GetRegionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegions>>,
          TError,
          Awaited<ReturnType<typeof getRegions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRegions<TData = Awaited<ReturnType<typeof getRegions>>, TError = ValidationExceptionResponse>(
 params?: GetRegionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegions>>,
          TError,
          Awaited<ReturnType<typeof getRegions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRegions<TData = Awaited<ReturnType<typeof getRegions>>, TError = ValidationExceptionResponse>(
 params?: GetRegionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegions>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a listing of the resource
 */

export function useGetRegions<TData = Awaited<ReturnType<typeof getRegions>>, TError = ValidationExceptionResponse>(
 params?: GetRegionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegions>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRegionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update the specified resource in storage
 */
export const updateRegion = (
    id: string,
    updateRegionBody: UpdateRegionBody,
 options?: SecondParameter<typeof apiInstance>,) => {
      
      
      return apiInstance<UpdateRegion200>(
      {url: `/regions/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateRegionBody
    },
      options);
    }
  


export const getUpdateRegionMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRegion>>, TError,{id: string;data: UpdateRegionBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateRegion>>, TError,{id: string;data: UpdateRegionBody}, TContext> => {

const mutationKey = ['updateRegion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRegion>>, {id: string;data: UpdateRegionBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRegion(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRegionMutationResult = NonNullable<Awaited<ReturnType<typeof updateRegion>>>
    export type UpdateRegionMutationBody = UpdateRegionBody
    export type UpdateRegionMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update the specified resource in storage
 */
export const useUpdateRegion = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRegion>>, TError,{id: string;data: UpdateRegionBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRegion>>,
        TError,
        {id: string;data: UpdateRegionBody},
        TContext
      > => {

      const mutationOptions = getUpdateRegionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Remove the specified resource from storage
 */
export const deleteRegion = (
    id: string,
 options?: SecondParameter<typeof apiInstance>,) => {
      
      
      return apiInstance<void>(
      {url: `/regions/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteRegionMutationOptions = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRegion>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRegion>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteRegion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRegion>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteRegion(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRegionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRegion>>>
    
    export type DeleteRegionMutationError = AuthenticationExceptionResponse

    /**
 * @summary Remove the specified resource from storage
 */
export const useDeleteRegion = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRegion>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRegion>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteRegionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Display the specified resource
 */
export const getRegionById = (
    id: string,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetRegionById200>(
      {url: `/regions/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetRegionByIdQueryKey = (id?: string,) => {
    return [
    `/regions/${id}`
    ] as const;
    }

    
export const getGetRegionByIdQueryOptions = <TData = Awaited<ReturnType<typeof getRegionById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegionById>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRegionByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRegionById>>> = ({ signal }) => getRegionById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRegionById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRegionByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getRegionById>>>
export type GetRegionByIdQueryError = unknown


export function useGetRegionById<TData = Awaited<ReturnType<typeof getRegionById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegionById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegionById>>,
          TError,
          Awaited<ReturnType<typeof getRegionById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRegionById<TData = Awaited<ReturnType<typeof getRegionById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegionById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegionById>>,
          TError,
          Awaited<ReturnType<typeof getRegionById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRegionById<TData = Awaited<ReturnType<typeof getRegionById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegionById>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display the specified resource
 */

export function useGetRegionById<TData = Awaited<ReturnType<typeof getRegionById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegionById>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRegionByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




