/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type {
    AuthenticationExceptionResponse,
    AuthorizationExceptionResponse,
    DeleteMedia200,
    GetMedias200,
    GetMediasParams,
    MediaResource,
    MediaUpdateRequest,
    ModelNotFoundExceptionResponse,
    StoreMediaRequest,
    ValidationExceptionResponse,
} from '.././model';

import { apiInstance } from '.././api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List media for an owner. Requires `owner_type` and `owner_id` unless platform admin
 */
export const getMedias = (
    params?: GetMediasParams,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<GetMedias200>(
        { url: `/medias`, method: 'GET', params, signal },
        options,
    );
};

export const getGetMediasQueryKey = (params?: GetMediasParams) => {
    return [`/medias`, ...(params ? [params] : [])] as const;
};

export const getGetMediasQueryOptions = <
    TData = Awaited<ReturnType<typeof getMedias>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ValidationExceptionResponse,
>(
    params?: GetMediasParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getMedias>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetMediasQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMedias>>> = ({
        signal,
    }) => getMedias(params, requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getMedias>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMediasQueryResult = NonNullable<
    Awaited<ReturnType<typeof getMedias>>
>;
export type GetMediasQueryError =
    | AuthenticationExceptionResponse
    | AuthorizationExceptionResponse
    | ValidationExceptionResponse;

export function useGetMedias<
    TData = Awaited<ReturnType<typeof getMedias>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ValidationExceptionResponse,
>(
    params: undefined | GetMediasParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getMedias>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getMedias>>,
                    TError,
                    Awaited<ReturnType<typeof getMedias>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMedias<
    TData = Awaited<ReturnType<typeof getMedias>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ValidationExceptionResponse,
>(
    params?: GetMediasParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getMedias>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getMedias>>,
                    TError,
                    Awaited<ReturnType<typeof getMedias>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMedias<
    TData = Awaited<ReturnType<typeof getMedias>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ValidationExceptionResponse,
>(
    params?: GetMediasParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getMedias>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List media for an owner. Requires `owner_type` and `owner_id` unless platform admin
 */

export function useGetMedias<
    TData = Awaited<ReturnType<typeof getMedias>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ValidationExceptionResponse,
>(
    params?: GetMediasParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getMedias>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetMediasQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Upload a file and create a media record
 */
export const createMedia = (
    storeMediaRequest: StoreMediaRequest,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    const formData = new FormData();
    formData.append(`owner_id`, storeMediaRequest.owner_id.toString());
    formData.append(`owner_type`, storeMediaRequest.owner_type);
    if (
        storeMediaRequest.name !== undefined &&
        storeMediaRequest.name !== null
    ) {
        formData.append(`name`, storeMediaRequest.name);
    }
    if (
        storeMediaRequest.description !== undefined &&
        storeMediaRequest.description !== null
    ) {
        formData.append(`description`, storeMediaRequest.description);
    }
    formData.append(`type`, storeMediaRequest.type);
    formData.append(`subtype`, storeMediaRequest.subtype);
    formData.append(`data`, storeMediaRequest.data);

    return apiInstance<MediaResource>(
        {
            url: `/medias`,
            method: 'POST',
            headers: { 'Content-Type': 'multipart/form-data' },
            data: formData,
            signal,
        },
        options,
    );
};

export const getCreateMediaMutationOptions = <
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ValidationExceptionResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createMedia>>,
        TError,
        { data: StoreMediaRequest },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createMedia>>,
    TError,
    { data: StoreMediaRequest },
    TContext
> => {
    const mutationKey = ['createMedia'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createMedia>>,
        { data: StoreMediaRequest }
    > = (props) => {
        const { data } = props ?? {};

        return createMedia(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateMediaMutationResult = NonNullable<
    Awaited<ReturnType<typeof createMedia>>
>;
export type CreateMediaMutationBody = StoreMediaRequest;
export type CreateMediaMutationError =
    | AuthenticationExceptionResponse
    | AuthorizationExceptionResponse
    | ValidationExceptionResponse;

/**
 * @summary Upload a file and create a media record
 */
export const useCreateMedia = <
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ValidationExceptionResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createMedia>>,
            TError,
            { data: StoreMediaRequest },
            TContext
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createMedia>>,
    TError,
    { data: StoreMediaRequest },
    TContext
> => {
    const mutationOptions = getCreateMediaMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get a single media item
 */
export const getMedia = (
    media: number,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<MediaResource>(
        { url: `/medias/${media}`, method: 'GET', signal },
        options,
    );
};

export const getGetMediaQueryKey = (media?: number) => {
    return [`/medias/${media}`] as const;
};

export const getGetMediaQueryOptions = <
    TData = Awaited<ReturnType<typeof getMedia>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ModelNotFoundExceptionResponse,
>(
    media: number,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getMedia>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetMediaQueryKey(media);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMedia>>> = ({
        signal,
    }) => getMedia(media, requestOptions, signal);

    return {
        queryKey,
        queryFn,
        enabled: !!media,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getMedia>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMediaQueryResult = NonNullable<
    Awaited<ReturnType<typeof getMedia>>
>;
export type GetMediaQueryError =
    | AuthenticationExceptionResponse
    | AuthorizationExceptionResponse
    | ModelNotFoundExceptionResponse;

export function useGetMedia<
    TData = Awaited<ReturnType<typeof getMedia>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ModelNotFoundExceptionResponse,
>(
    media: number,
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getMedia>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getMedia>>,
                    TError,
                    Awaited<ReturnType<typeof getMedia>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMedia<
    TData = Awaited<ReturnType<typeof getMedia>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ModelNotFoundExceptionResponse,
>(
    media: number,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getMedia>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getMedia>>,
                    TError,
                    Awaited<ReturnType<typeof getMedia>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMedia<
    TData = Awaited<ReturnType<typeof getMedia>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ModelNotFoundExceptionResponse,
>(
    media: number,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getMedia>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a single media item
 */

export function useGetMedia<
    TData = Awaited<ReturnType<typeof getMedia>>,
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ModelNotFoundExceptionResponse,
>(
    media: number,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getMedia>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetMediaQueryOptions(media, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Update media metadata (name, description)
 */
export const updateMedia = (
    media: number,
    mediaUpdateRequest: MediaUpdateRequest,
    options?: SecondParameter<typeof apiInstance>,
) => {
    return apiInstance<MediaResource>(
        {
            url: `/medias/${media}`,
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            data: mediaUpdateRequest,
        },
        options,
    );
};

export const getUpdateMediaMutationOptions = <
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ModelNotFoundExceptionResponse
        | ValidationExceptionResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateMedia>>,
        TError,
        { media: number; data: MediaUpdateRequest },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateMedia>>,
    TError,
    { media: number; data: MediaUpdateRequest },
    TContext
> => {
    const mutationKey = ['updateMedia'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateMedia>>,
        { media: number; data: MediaUpdateRequest }
    > = (props) => {
        const { media, data } = props ?? {};

        return updateMedia(media, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateMediaMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateMedia>>
>;
export type UpdateMediaMutationBody = MediaUpdateRequest;
export type UpdateMediaMutationError =
    | AuthenticationExceptionResponse
    | AuthorizationExceptionResponse
    | ModelNotFoundExceptionResponse
    | ValidationExceptionResponse;

/**
 * @summary Update media metadata (name, description)
 */
export const useUpdateMedia = <
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ModelNotFoundExceptionResponse
        | ValidationExceptionResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateMedia>>,
            TError,
            { media: number; data: MediaUpdateRequest },
            TContext
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof updateMedia>>,
    TError,
    { media: number; data: MediaUpdateRequest },
    TContext
> => {
    const mutationOptions = getUpdateMediaMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a media item and its stored files
 */
export const deleteMedia = (
    media: number,
    options?: SecondParameter<typeof apiInstance>,
) => {
    return apiInstance<DeleteMedia200>(
        { url: `/medias/${media}`, method: 'DELETE' },
        options,
    );
};

export const getDeleteMediaMutationOptions = <
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ModelNotFoundExceptionResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteMedia>>,
        TError,
        { media: number },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteMedia>>,
    TError,
    { media: number },
    TContext
> => {
    const mutationKey = ['deleteMedia'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteMedia>>,
        { media: number }
    > = (props) => {
        const { media } = props ?? {};

        return deleteMedia(media, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteMediaMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteMedia>>
>;

export type DeleteMediaMutationError =
    | AuthenticationExceptionResponse
    | AuthorizationExceptionResponse
    | ModelNotFoundExceptionResponse;

/**
 * @summary Delete a media item and its stored files
 */
export const useDeleteMedia = <
    TError =
        | AuthenticationExceptionResponse
        | AuthorizationExceptionResponse
        | ModelNotFoundExceptionResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteMedia>>,
            TError,
            { media: number },
            TContext
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof deleteMedia>>,
    TError,
    { media: number },
    TContext
> => {
    const mutationOptions = getDeleteMediaMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
