; =========================
; TravelBoost DEV - Queue Worker
; =========================
[program:travelboost-dev-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/travelboost/travelboost-dev/artisan queue:work --sleep=3 --tries=3 --timeout=90
directory=/home/travelboost/travelboost-dev
autostart=true
autorestart=true
user=travelboost
numprocs=1
redirect_stderr=true
stdout_logfile=/home/travelboost/travelboost-dev/storage/logs/worker.log
stopwaitsecs=3600

; =========================
; TravelBoost DEV - Scheduler
; =========================
[program:travelboost-dev-scheduler]
command=/usr/bin/php /home/travelboost/travelboost-dev/artisan schedule:work
directory=/home/travelboost/travelboost-dev
autostart=true
autorestart=true
user=travelboost
redirect_stderr=true
stdout_logfile=/home/travelboost/travelboost-dev/storage/logs/scheduler.log
stopwaitsecs=3600

; =========================
; TravelBoost DEV - Reverb
; =========================
[program:travelboost-dev-reverb]
command=/usr/bin/php /home/travelboost/travelboost-dev/artisan reverb:start --host=127.0.0.1 --port=8080
directory=/home/travelboost/travelboost-dev
autostart=true
autorestart=true
user=travelboost
redirect_stderr=true
stdout_logfile=/home/travelboost/travelboost-dev/storage/logs/reverb.log