; =========================
; Queue Worker
; =========================
[program:queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/travelboost/travelboost/artisan queue:work --sleep=3 --tries=3 --timeout=90
directory=/home/travelboost/travelboost
autostart=true
autorestart=true
user=travelboost
numprocs=1
redirect_stderr=true
stdout_logfile=/home/travelboost/travelboost/storage/logs/queue-worker.log
stopwaitsecs=3600

; =========================
; Scheduler
; =========================
[program:scheduler]
command=/usr/bin/php /home/travelboost/travelboost/artisan schedule:work
directory=/home/travelboost/travelboost
autostart=true
autorestart=true
user=travelboost
redirect_stderr=true
stdout_logfile=/home/travelboost/travelboost/storage/logs/scheduler.log
stopwaitsecs=3600

; =========================
; Reverb
; =========================
[program:reverb]
command=/usr/bin/php /home/travelboost/travelboost/artisan reverb:start --host=127.0.0.1 --port=8080
directory=/home/travelboost/travelboost
autostart=true
autorestart=true
user=travelboost
redirect_stderr=true
stdout_logfile=/home/travelboost/travelboost/storage/logs/reverb.log