; =========================
; TravelBoost MAIN - Queue Worker
; =========================
[program:travelboost-main-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/travelboost/travelboost-main/artisan queue:work --sleep=3 --tries=3 --timeout=90
directory=/home/travelboost/travelboost-main
autostart=true
autorestart=true
user=travelboost
numprocs=1
redirect_stderr=true
stdout_logfile=/home/travelboost/travelboost-main/storage/logs/worker.log
stopwaitsecs=3600

; =========================
; TravelBoost MAIN - Scheduler
; =========================
[program:travelboost-main-scheduler]
command=/usr/bin/php /home/travelboost/travelboost-main/artisan schedule:work
directory=/home/travelboost/travelboost-main
autostart=true
autorestart=true
user=travelboost
redirect_stderr=true
stdout_logfile=/home/travelboost/travelboost-main/storage/logs/scheduler.log
stopwaitsecs=3600

; =========================
; TravelBoost MAIN - Reverb
; =========================
[program:travelboost-main-reverb]
command=/usr/bin/php /home/travelboost/travelboost-main/artisan reverb:start --host=127.0.0.1 --port=8081
directory=/home/travelboost/travelboost-main
autostart=true
autorestart=true
user=travelboost
redirect_stderr=true
stdout_logfile=/home/travelboost/travelboost-main/storage/logs/reverb.log