/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  CreateContinent201,
  CreateContinentBody,
  GetContinentById200,
  GetContinents200,
  GetContinentsParams,
  UpdateContinent200,
  UpdateContinentBody,
  ValidationExceptionResponse
} from '.././model';

import { apiInstance } from '.././api-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Store a newly created resource in storage
 */
export const createContinent = (
    createContinentBody: CreateContinentBody,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<CreateContinent201>(
      {url: `/continents`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createContinentBody, signal
    },
      options);
    }
  


export const getCreateContinentMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContinent>>, TError,{data: CreateContinentBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createContinent>>, TError,{data: CreateContinentBody}, TContext> => {

const mutationKey = ['createContinent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createContinent>>, {data: CreateContinentBody}> = (props) => {
          const {data} = props ?? {};

          return  createContinent(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateContinentMutationResult = NonNullable<Awaited<ReturnType<typeof createContinent>>>
    export type CreateContinentMutationBody = CreateContinentBody
    export type CreateContinentMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Store a newly created resource in storage
 */
export const useCreateContinent = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContinent>>, TError,{data: CreateContinentBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createContinent>>,
        TError,
        {data: CreateContinentBody},
        TContext
      > => {

      const mutationOptions = getCreateContinentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Display a listing of the resource
 */
export const getContinents = (
    params?: GetContinentsParams,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetContinents200>(
      {url: `/continents`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetContinentsQueryKey = (params?: GetContinentsParams,) => {
    return [
    `/continents`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetContinentsQueryOptions = <TData = Awaited<ReturnType<typeof getContinents>>, TError = ValidationExceptionResponse>(params?: GetContinentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinents>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContinentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContinents>>> = ({ signal }) => getContinents(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContinents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContinentsQueryResult = NonNullable<Awaited<ReturnType<typeof getContinents>>>
export type GetContinentsQueryError = ValidationExceptionResponse


export function useGetContinents<TData = Awaited<ReturnType<typeof getContinents>>, TError = ValidationExceptionResponse>(
 params: undefined |  GetContinentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContinents>>,
          TError,
          Awaited<ReturnType<typeof getContinents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContinents<TData = Awaited<ReturnType<typeof getContinents>>, TError = ValidationExceptionResponse>(
 params?: GetContinentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContinents>>,
          TError,
          Awaited<ReturnType<typeof getContinents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContinents<TData = Awaited<ReturnType<typeof getContinents>>, TError = ValidationExceptionResponse>(
 params?: GetContinentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinents>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a listing of the resource
 */

export function useGetContinents<TData = Awaited<ReturnType<typeof getContinents>>, TError = ValidationExceptionResponse>(
 params?: GetContinentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinents>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContinentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update the specified resource in storage
 */
export const updateContinent = (
    id: string,
    updateContinentBody: UpdateContinentBody,
 options?: SecondParameter<typeof apiInstance>,) => {
      
      
      return apiInstance<UpdateContinent200>(
      {url: `/continents/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateContinentBody
    },
      options);
    }
  


export const getUpdateContinentMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContinent>>, TError,{id: string;data: UpdateContinentBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateContinent>>, TError,{id: string;data: UpdateContinentBody}, TContext> => {

const mutationKey = ['updateContinent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateContinent>>, {id: string;data: UpdateContinentBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateContinent(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateContinentMutationResult = NonNullable<Awaited<ReturnType<typeof updateContinent>>>
    export type UpdateContinentMutationBody = UpdateContinentBody
    export type UpdateContinentMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update the specified resource in storage
 */
export const useUpdateContinent = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContinent>>, TError,{id: string;data: UpdateContinentBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateContinent>>,
        TError,
        {id: string;data: UpdateContinentBody},
        TContext
      > => {

      const mutationOptions = getUpdateContinentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Remove the specified resource from storage
 */
export const deleteContinent = (
    id: string,
 options?: SecondParameter<typeof apiInstance>,) => {
      
      
      return apiInstance<void>(
      {url: `/continents/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteContinentMutationOptions = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContinent>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContinent>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteContinent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContinent>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteContinent(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteContinentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContinent>>>
    
    export type DeleteContinentMutationError = AuthenticationExceptionResponse

    /**
 * @summary Remove the specified resource from storage
 */
export const useDeleteContinent = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContinent>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContinent>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteContinentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Display the specified resource
 */
export const getContinentById = (
    id: string,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetContinentById200>(
      {url: `/continents/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetContinentByIdQueryKey = (id?: string,) => {
    return [
    `/continents/${id}`
    ] as const;
    }

    
export const getGetContinentByIdQueryOptions = <TData = Awaited<ReturnType<typeof getContinentById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinentById>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContinentByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContinentById>>> = ({ signal }) => getContinentById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContinentById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContinentByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getContinentById>>>
export type GetContinentByIdQueryError = unknown


export function useGetContinentById<TData = Awaited<ReturnType<typeof getContinentById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinentById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContinentById>>,
          TError,
          Awaited<ReturnType<typeof getContinentById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContinentById<TData = Awaited<ReturnType<typeof getContinentById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinentById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContinentById>>,
          TError,
          Awaited<ReturnType<typeof getContinentById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContinentById<TData = Awaited<ReturnType<typeof getContinentById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinentById>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display the specified resource
 */

export function useGetContinentById<TData = Awaited<ReturnType<typeof getContinentById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContinentById>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContinentByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




