/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * Travelboost JSON API consumed by the React client at `/webapi`.

Only routes under `/webapi` are documented here (see `config/scramble.php`).

After changing Webapi controllers, Form Requests, or API Resources, run `pnpm orval` to regenerate TypeScript clients. See `docs/webapi-orval.md`.
 * OpenAPI spec version: 0.0.1
 */
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type {
    AuthenticationExceptionResponse,
    CreateAgentSubscriptionPayment200,
    CreateAgentSubscriptionPaymentBody,
    CreateAiCreditTopupPayment200,
    CreateAiCreditTopupPaymentBody,
    CreateTopupPayment200,
    CreateTopupPayment409,
    CreateTopupPaymentBody,
    GetPayments200,
    GetPaymentsParams,
    ModelNotFoundExceptionResponse,
    SyncPaymentStatus200,
    SyncPaymentStatus422,
    ValidationExceptionResponse,
} from '.././model';

import { apiInstance } from '.././api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Sync payment status from the gateway
 */
export const syncPaymentStatus = (
    payment: number,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<SyncPaymentStatus200>(
        { url: `/payments/${payment}/sync-status`, method: 'POST', signal },
        options,
    );
};

export const getSyncPaymentStatusMutationOptions = <
    TError =
        | AuthenticationExceptionResponse
        | ModelNotFoundExceptionResponse
        | SyncPaymentStatus422,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof syncPaymentStatus>>,
        TError,
        { payment: number },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof syncPaymentStatus>>,
    TError,
    { payment: number },
    TContext
> => {
    const mutationKey = ['syncPaymentStatus'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof syncPaymentStatus>>,
        { payment: number }
    > = (props) => {
        const { payment } = props ?? {};

        return syncPaymentStatus(payment, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type SyncPaymentStatusMutationResult = NonNullable<
    Awaited<ReturnType<typeof syncPaymentStatus>>
>;

export type SyncPaymentStatusMutationError =
    | AuthenticationExceptionResponse
    | ModelNotFoundExceptionResponse
    | SyncPaymentStatus422;

/**
 * @summary Sync payment status from the gateway
 */
export const useSyncPaymentStatus = <
    TError =
        | AuthenticationExceptionResponse
        | ModelNotFoundExceptionResponse
        | SyncPaymentStatus422,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof syncPaymentStatus>>,
            TError,
            { payment: number },
            TContext
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof syncPaymentStatus>>,
    TError,
    { payment: number },
    TContext
> => {
    const mutationOptions = getSyncPaymentStatusMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * @summary get payment list
 */
export const getPayments = (
    params?: GetPaymentsParams,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<GetPayments200>(
        { url: `/payments`, method: 'GET', params, signal },
        options,
    );
};

export const getGetPaymentsQueryKey = (params?: GetPaymentsParams) => {
    return [`/payments`, ...(params ? [params] : [])] as const;
};

export const getGetPaymentsQueryOptions = <
    TData = Awaited<ReturnType<typeof getPayments>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: GetPaymentsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPayments>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetPaymentsQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPayments>>> = ({
        signal,
    }) => getPayments(params, requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getPayments>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPaymentsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getPayments>>
>;
export type GetPaymentsQueryError =
    | AuthenticationExceptionResponse
    | ValidationExceptionResponse;

export function useGetPayments<
    TData = Awaited<ReturnType<typeof getPayments>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params: undefined | GetPaymentsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPayments>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getPayments>>,
                    TError,
                    Awaited<ReturnType<typeof getPayments>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPayments<
    TData = Awaited<ReturnType<typeof getPayments>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: GetPaymentsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPayments>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getPayments>>,
                    TError,
                    Awaited<ReturnType<typeof getPayments>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPayments<
    TData = Awaited<ReturnType<typeof getPayments>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: GetPaymentsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPayments>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary get payment list
 */

export function useGetPayments<
    TData = Awaited<ReturnType<typeof getPayments>>,
    TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
>(
    params?: GetPaymentsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPayments>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetPaymentsQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Create wallet topup payment
 */
export const createTopupPayment = (
    createTopupPaymentBody: CreateTopupPaymentBody,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<CreateTopupPayment200>(
        {
            url: `/payments/create-topup-payment`,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            data: createTopupPaymentBody,
            signal,
        },
        options,
    );
};

export const getCreateTopupPaymentMutationOptions = <
    TError =
        | ModelNotFoundExceptionResponse
        | CreateTopupPayment409
        | ValidationExceptionResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createTopupPayment>>,
        TError,
        { data: CreateTopupPaymentBody },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createTopupPayment>>,
    TError,
    { data: CreateTopupPaymentBody },
    TContext
> => {
    const mutationKey = ['createTopupPayment'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createTopupPayment>>,
        { data: CreateTopupPaymentBody }
    > = (props) => {
        const { data } = props ?? {};

        return createTopupPayment(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateTopupPaymentMutationResult = NonNullable<
    Awaited<ReturnType<typeof createTopupPayment>>
>;
export type CreateTopupPaymentMutationBody = CreateTopupPaymentBody;
export type CreateTopupPaymentMutationError =
    | ModelNotFoundExceptionResponse
    | CreateTopupPayment409
    | ValidationExceptionResponse;

/**
 * @summary Create wallet topup payment
 */
export const useCreateTopupPayment = <
    TError =
        | ModelNotFoundExceptionResponse
        | CreateTopupPayment409
        | ValidationExceptionResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createTopupPayment>>,
            TError,
            { data: CreateTopupPaymentBody },
            TContext
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createTopupPayment>>,
    TError,
    { data: CreateTopupPaymentBody },
    TContext
> => {
    const mutationOptions = getCreateTopupPaymentMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Create payment for agent subscription
 */
export const createAgentSubscriptionPayment = (
    createAgentSubscriptionPaymentBody: CreateAgentSubscriptionPaymentBody,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<CreateAgentSubscriptionPayment200>(
        {
            url: `/payments/create-agent-subscription-payment`,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            data: createAgentSubscriptionPaymentBody,
            signal,
        },
        options,
    );
};

export const getCreateAgentSubscriptionPaymentMutationOptions = <
    TError = ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createAgentSubscriptionPayment>>,
        TError,
        { data: CreateAgentSubscriptionPaymentBody },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createAgentSubscriptionPayment>>,
    TError,
    { data: CreateAgentSubscriptionPaymentBody },
    TContext
> => {
    const mutationKey = ['createAgentSubscriptionPayment'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createAgentSubscriptionPayment>>,
        { data: CreateAgentSubscriptionPaymentBody }
    > = (props) => {
        const { data } = props ?? {};

        return createAgentSubscriptionPayment(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateAgentSubscriptionPaymentMutationResult = NonNullable<
    Awaited<ReturnType<typeof createAgentSubscriptionPayment>>
>;
export type CreateAgentSubscriptionPaymentMutationBody =
    CreateAgentSubscriptionPaymentBody;
export type CreateAgentSubscriptionPaymentMutationError =
    | ModelNotFoundExceptionResponse
    | ValidationExceptionResponse;

/**
 * @summary Create payment for agent subscription
 */
export const useCreateAgentSubscriptionPayment = <
    TError = ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createAgentSubscriptionPayment>>,
            TError,
            { data: CreateAgentSubscriptionPaymentBody },
            TContext
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createAgentSubscriptionPayment>>,
    TError,
    { data: CreateAgentSubscriptionPaymentBody },
    TContext
> => {
    const mutationOptions =
        getCreateAgentSubscriptionPaymentMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Create payment for AI credit topup
 */
export const createAiCreditTopupPayment = (
    createAiCreditTopupPaymentBody: CreateAiCreditTopupPaymentBody,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<CreateAiCreditTopupPayment200>(
        {
            url: `/payments/create-ai-credit-topup-payment`,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            data: createAiCreditTopupPaymentBody,
            signal,
        },
        options,
    );
};

export const getCreateAiCreditTopupPaymentMutationOptions = <
    TError =
        | AuthenticationExceptionResponse
        | ModelNotFoundExceptionResponse
        | ValidationExceptionResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createAiCreditTopupPayment>>,
        TError,
        { data: CreateAiCreditTopupPaymentBody },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createAiCreditTopupPayment>>,
    TError,
    { data: CreateAiCreditTopupPaymentBody },
    TContext
> => {
    const mutationKey = ['createAiCreditTopupPayment'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createAiCreditTopupPayment>>,
        { data: CreateAiCreditTopupPaymentBody }
    > = (props) => {
        const { data } = props ?? {};

        return createAiCreditTopupPayment(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateAiCreditTopupPaymentMutationResult = NonNullable<
    Awaited<ReturnType<typeof createAiCreditTopupPayment>>
>;
export type CreateAiCreditTopupPaymentMutationBody =
    CreateAiCreditTopupPaymentBody;
export type CreateAiCreditTopupPaymentMutationError =
    | AuthenticationExceptionResponse
    | ModelNotFoundExceptionResponse
    | ValidationExceptionResponse;

/**
 * @summary Create payment for AI credit topup
 */
export const useCreateAiCreditTopupPayment = <
    TError =
        | AuthenticationExceptionResponse
        | ModelNotFoundExceptionResponse
        | ValidationExceptionResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createAiCreditTopupPayment>>,
            TError,
            { data: CreateAiCreditTopupPaymentBody },
            TContext
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createAiCreditTopupPayment>>,
    TError,
    { data: CreateAiCreditTopupPaymentBody },
    TContext
> => {
    const mutationOptions =
        getCreateAiCreditTopupPaymentMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
