/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  CreateTopupPayment200,
  CreateTopupPaymentBody,
  GetPayments200,
  GetPaymentsParams,
  ValidationExceptionResponse
} from '.././model';

import { apiInstance } from '.././api-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary get payment list
 */
export const getPayments = (
    params?: GetPaymentsParams,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetPayments200>(
      {url: `/payments`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetPaymentsQueryKey = (params?: GetPaymentsParams,) => {
    return [
    `/payments`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetPaymentsQueryOptions = <TData = Awaited<ReturnType<typeof getPayments>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(params?: GetPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayments>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPaymentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPayments>>> = ({ signal }) => getPayments(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPayments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPaymentsQueryResult = NonNullable<Awaited<ReturnType<typeof getPayments>>>
export type GetPaymentsQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse


export function useGetPayments<TData = Awaited<ReturnType<typeof getPayments>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  GetPaymentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPayments>>,
          TError,
          Awaited<ReturnType<typeof getPayments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPayments<TData = Awaited<ReturnType<typeof getPayments>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params?: GetPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPayments>>,
          TError,
          Awaited<ReturnType<typeof getPayments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPayments<TData = Awaited<ReturnType<typeof getPayments>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params?: GetPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayments>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary get payment list
 */

export function useGetPayments<TData = Awaited<ReturnType<typeof getPayments>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 params?: GetPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayments>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPaymentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create wallet topup payment (Midtrans Snap)
 */
export const createTopupPayment = (
    createTopupPaymentBody: CreateTopupPaymentBody,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<CreateTopupPayment200>(
      {url: `/payments/topup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTopupPaymentBody, signal
    },
      options);
    }
  


export const getCreateTopupPaymentMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTopupPayment>>, TError,{data: CreateTopupPaymentBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createTopupPayment>>, TError,{data: CreateTopupPaymentBody}, TContext> => {

const mutationKey = ['createTopupPayment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTopupPayment>>, {data: CreateTopupPaymentBody}> = (props) => {
          const {data} = props ?? {};

          return  createTopupPayment(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTopupPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof createTopupPayment>>>
    export type CreateTopupPaymentMutationBody = CreateTopupPaymentBody
    export type CreateTopupPaymentMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Create wallet topup payment (Midtrans Snap)
 */
export const useCreateTopupPayment = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTopupPayment>>, TError,{data: CreateTopupPaymentBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTopupPayment>>,
        TError,
        {data: CreateTopupPaymentBody},
        TContext
      > => {

      const mutationOptions = getCreateTopupPaymentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    