<?php

namespace Database\Seeders\Production;

class IslamicChinaTravelTourSeeder extends ProductionTourCatalogSeeder
{
    protected function vendorUsername(): string
    {
        return 'islamicchinatravel';
    }

    protected function tours(): array
    {
        return [
            [
                'code' => 'ICT-001-001',
                'name' => '8D Lingshan Wangxian Valley',
                'description' => 'NANJING WUYUAN WANGXIAN VALLEY SHENXIANJU HANGZHOU SHANGHAI MUSLIM',
                'duration_days' => 8,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - NANJING WUYUAN WANGXIAN VALLEY SHENXIANJU HANGZHOU SHANGHAI MUSLIM',
                'product_commission_category' => 'Umum',
                'showprice' => 11280000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 850000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN: 13 SEP: 05, 12 OCT: 10',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13580000,
                            'Adult Double' => 11280000,
                            'Adult Twin' => 11280000,
                            'Adult Extra Bed' => 11280000,
                            'Child With Bed' => 11280000,
                            'Child No Bed' => 10980000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUNI : 20,27',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 17500000,
                            'Adult Double' => 12080000,
                            'Adult Twin' => 12080000,
                            'Adult Extra Bed' => 12080000,
                            'Child With Bed' => 12080000,
                            'Child No Bed' => 14380000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-001-002',
                'name' => '8D NANJING WUXI SUZHOU',
                'description' => 'NANJING WUXI SUZHOU SHANGHAI HANGZHOU MUSLIM',
                'duration_days' => 8,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - NANJING WUXI SUZHOU SHANGHAI HANGZHOU MUSLIM',
                'product_commission_category' => 'Umum',
                'showprice' => 9280000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 850000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN: 11 SEP: 03, 10, 17 OCT: 15, 22',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 11380000,
                            'Adult Double' => 9280000,
                            'Adult Twin' => 9280000,
                            'Adult Extra Bed' => 9280000,
                            'Child With Bed' => 9280000,
                            'Child No Bed' => 8980000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 18, 25 OCT: 08',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 12180000,
                            'Adult Double' => 10080000,
                            'Adult Twin' => 10080000,
                            'Adult Extra Bed' => 10080000,
                            'Child With Bed' => 10080000,
                            'Child No Bed' => 9780000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-001-003',
                'name' => '8D NANJING HUANGSHAN WUYUAN SHANGRAO HANGZHOU SHANGHAI MUSLIM',
                'description' => 'NANJING HUANGSHAN WUYUAN SHANGRAO HANGZHOU SHANGHAI MUSLIM',
                'duration_days' => 8,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - NANJING HUANGSHAN WUYUAN SHANGRAO HANGZHOU SHANGHAI MUSLIM',
                'product_commission_category' => 'Umum',
                'showprice' => 11280000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 850000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN: 13 SEP: 05, 12 OCT: 10',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13580000,
                            'Adult Double' => 11280000,
                            'Adult Twin' => 11280000,
                            'Adult Extra Bed' => 11280000,
                            'Child With Bed' => 11280000,
                            'Child No Bed' => 10980000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => '*JUN : 20, 27',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14380000,
                            'Adult Double' => 12080000,
                            'Adult Twin' => 12080000,
                            'Adult Extra Bed' => 12080000,
                            'Child With Bed' => 12080000,
                            'Child No Bed' => 11780000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-001-004',
                'name' => '6D BEST SAVER MUSLIM NANJING HUANGSHAN HANGZHOU SHANGHAI',
                'description' => '6D BEST SAVER MUSLIM NANJING HUANGSHAN HANGZHOU SHANGHAI',
                'duration_days' => 6,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - NANJING HUANGSHAN HANGZHOU SHANGHAI',
                'product_commission_category' => 'Umum',
                'showprice' => 8180000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 650000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'SEP: 03, 10, 17 OCT: 15, 22',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 9980000,
                            'Adult Double' => 8180000,
                            'Adult Twin' => 8180000,
                            'Adult Extra Bed' => 8180000,
                            'Child With Bed' => 8180000,
                            'Child No Bed' => 7980000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 18, 25 OCT: 08',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 10880000,
                            'Adult Double' => 9080000,
                            'Adult Twin' => 9080000,
                            'Adult Extra Bed' => 9080000,
                            'Child With Bed' => 9080000,
                            'Child No Bed' => 8680000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-002-001',
                'name' => '9D GANSU MUSLIM',
                'description' => '9D GANSU MUSLIM',
                'duration_days' => 9,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - DUNHUANG - JIAYUGUAN - JIUQUAN - SUNAN - ZHANGYE',
                'product_commission_category' => 'Umum',
                'showprice' => 12900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 850000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => '*JUN: 12, 19',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 15700000,
                            'Adult Double' => 12900000,
                            'Adult Twin' => 12900000,
                            'Adult Extra Bed' => 12900000,
                            'Child With Bed' => 12900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-003-001',
                'name' => '9D INNER MONGOLIA MUSLIM',
                'description' => '9D INNER MONGOLIA MUSLIM',
                'duration_days' => 9,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - ORDOS - HOHHOT - ORDOS GRASSLAND',
                'product_commission_category' => 'Umum',
                'showprice' => 11500000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 850000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => '*SEP: 3 OCT: 1',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14300000,
                            'Adult Double' => 11500000,
                            'Adult Twin' => 11500000,
                            'Adult Extra Bed' => 11500000,
                            'Child With Bed' => 11500000,
                            'Child No Bed' => 9775000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => '*OCT: 1, 8',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14300000,
                            'Adult Double' => 11500000,
                            'Adult Twin' => 11500000,
                            'Adult Extra Bed' => 11500000,
                            'Child With Bed' => 11500000,
                            'Child No Bed' => 9775000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-004-001',
                'name' => '8D SHANGRILA MUSLIM',
                'description' => '8D SHANGRILA MUSLIM',
                'duration_days' => 8,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - KUNMING - DALI - LIJIANG - SHANGRILA',
                'product_commission_category' => 'Umum',
                'showprice' => 10900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 748000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN : 11, 13, 15 SEP: 3, 5, 8, 10, 12, 15, 17, 19, 22, 24, 26, 29 OCT: 1, 3, 6, 8, 10, 13, 15, 17, 20, 22, 24, 27, 29, 31 NOV: 3, 5, 7, 10, 12, 14, 17, 19, 21, 24, 26, 28 DEC: 1, 3, 5, 8, 10, 12, 15',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13100000,
                            'Adult Double' => 10900000,
                            'Adult Twin' => 10900000,
                            'Adult Extra Bed' => 10900000,
                            'Child With Bed' => 10900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'NOV: 3, 5, 7, 10, 12, 14, 17, 19, 21, 24, 26, 28 DEC: 1, 3, 5, 8, 10, 12, 15',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13100000,
                            'Adult Double' => 10900000,
                            'Adult Twin' => 10900000,
                            'Adult Extra Bed' => 10900000,
                            'Child With Bed' => 10900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'HIGH SEASON JUN: 18, 20, 22, 25, 27',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14100000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-004-002',
                'name' => '8D KUNMING DALI LIJIANG SHANGRILA + BALAGEZONG MUSLIM',
                'description' => '8D KUNMING DALI LIJIANG SHANGRILA + BALAGEZONG MUSLIM',
                'duration_days' => 8,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - KUNMING - DALI - LIJIANG - SHANGRILA - BALAGEZONG',
                'product_commission_category' => 'Umum',
                'showprice' => 11900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 748000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN : 11, 13, 15 SEP: 3, 5, 8, 10, 12, 15, 17, 19, 22, 24, 26, 29 OCT: 1, 3, 6, 8, 10, 13, 15, 17, 20, 22, 24, 27, 29, 31 NOV: 3, 5, 7, 10, 12, 14, 17, 19, 21, 24, 26, 28 DEC: 1, 3, 5, 8, 10, 12, 15',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14100000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'NOV: 3, 5, 7, 10, 12, 14, 17, 19, 21, 24, 26, 28 DEC: 1, 3, 5, 8, 10, 12, 15',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14100000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'HIGH SEASON JUN: 18, 20, 22, 25, 27',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 15100000,
                            'Adult Double' => 12900000,
                            'Adult Twin' => 12900000,
                            'Adult Extra Bed' => 12900000,
                            'Child With Bed' => 12900000,
                            'Child No Bed' => 10965000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-004-003',
                'name' => '8D BALAGEZONG SHANGRILA MUSLIM',
                'description' => '8D BALAGEZONG SHANGRILA MUSLIM',
                'duration_days' => 8,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - KUNMING - DALI - LIJIANG - BALAGEZONG - SHANGRILA',
                'product_commission_category' => 'Umum',
                'showprice' => 10900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 748000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN : 11, 13, 15 SEP: 3, 5, 8, 10, 12, 15, 17, 19, 22, 24, 26, 29 OCT: 1, 3, 6, 8, 10, 13, 15, 17, 20, 22, 24, 27, 29, 31 NOV: 3, 5, 7, 10, 12, 14, 17, 19, 21, 24, 26, 28 DEC: 1, 3, 5, 8, 10, 12, 15',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13100000,
                            'Adult Double' => 10900000,
                            'Adult Twin' => 10900000,
                            'Adult Extra Bed' => 10900000,
                            'Child With Bed' => 10900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'NOV: 3, 5, 7, 10, 12, 14, 17, 19, 21, 24, 26, 28 DEC: 1, 3, 5, 8, 10, 12, 15',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13100000,
                            'Adult Double' => 10900000,
                            'Adult Twin' => 10900000,
                            'Adult Extra Bed' => 10900000,
                            'Child With Bed' => 10900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'HIGH SEASON JUN: 18, 20, 22, 25, 27',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14100000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-004-004',
                'name' => '8D KUNMING CHONGQING WULONG MUSLIM KUNMING - CHONGQING - WULONG',
                'description' => '8D KUNMING CHONGQING WULONG MUSLIM KUNMING - CHONGQING - WULONG',
                'duration_days' => 8,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - KUNMING - CHONGQING - WULONG',
                'product_commission_category' => 'Umum',
                'showprice' => 11900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 748000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN : 11, 13, 15 SEP: 3, 5, 8, 10, 12, 15, 17, 19, 22, 24, 26, 29 OCT: 1, 3, 6, 8, 10, 13, 15, 17, 20, 22, 24, 27, 29, 31 NOV: 3, 5, 7, 10, 12, 14, 17, 19, 21, 24, 26, 28 DEC: 1, 3, 5, 8, 10, 12, 15',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14100000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'NOV: 3, 5, 7, 10, 12, 14, 17, 19, 21, 24, 26, 28 DEC: 1, 3, 5, 8, 10, 12, 15',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14100000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'HIGH SEASON JUN: 18, 20, 22, 25, 27',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 15100000,
                            'Adult Double' => 12900000,
                            'Adult Twin' => 12900000,
                            'Adult Extra Bed' => 12900000,
                            'Child With Bed' => 12900000,
                            'Child No Bed' => 10965000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-005-001',
                'name' => '9D CHONGQING SCHOOL HOLIDAY MUSLIM',
                'description' => '9D CHONGQING SCHOOL HOLIDAY MUSLIM',
                'duration_days' => 8,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - CHONGQING - YONGCHUAN - CHENGDU - DUJIANGYAN - CHONGQING',
                'product_commission_category' => 'Umum',
                'showprice' => 11900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 782000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN: 18, 19, 20, 30 JUL: 2, 3, 5',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14100000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 21, 23, 25, 26, 27, 28',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 15100000,
                            'Adult Double' => 12900000,
                            'Adult Twin' => 12900000,
                            'Adult Extra Bed' => 12900000,
                            'Child With Bed' => 12900000,
                            'Child No Bed' => 10965000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-005-002',
                'name' => '9D CHENGDU PANDA VALLEY MUSLIM',
                'description' => '9D CHENGDU PANDA VALLEY MUSLIM',
                'duration_days' => 8,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - CHONGQING - CHENGDU - DUJIANGYAN - DAZU',
                'product_commission_category' => 'Umum',
                'showprice' => 10900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 782000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN: 14, 16 JUL: 10, 12, 17, 19, 24, 25, 26, 31 AUG: 1, 2, 7, 8, 9, 14, 15, 16, 21, 22, 23, 28, 29, 30 SEP: 1, 3, 4, 5, 6, 8, 10, 11, 12, 13, 15, 17, 18, 19, 20, 22, 24, 25 OCT: 9, 10, 11, 13, 15, 16, 17, 18, 20, 22, 23, 24, 25, 27, 29, 30, 31',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13100000,
                            'Adult Double' => 10900000,
                            'Adult Twin' => 10900000,
                            'Adult Extra Bed' => 10900000,
                            'Child With Bed' => 10900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'SEP: 1, 3, 4, 5, 6, 8, 10, 11, 12, 13, 15, 17, 18, 19, 20, 22, 24, 25 OCT: 9, 10, 11, 13, 15, 16, 17, 18, 20, 22, 23, 24, 25, 27, 29, 30, 31',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13100000,
                            'Adult Double' => 10900000,
                            'Adult Twin' => 10900000,
                            'Adult Extra Bed' => 10900000,
                            'Child With Bed' => 10900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 18, 19, 20, 30 JUL: 2, 3, 5',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14100000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 21, 23, 25, 26, 27, 28',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 15100000,
                            'Adult Double' => 12900000,
                            'Adult Twin' => 12900000,
                            'Adult Extra Bed' => 12900000,
                            'Child With Bed' => 12900000,
                            'Child No Bed' => 10965000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-005-003',
                'name' => '9D XI\'AN TERRACOTTA WARRIORS MUSLIM',
                'description' => '9D XI\'AN TERRACOTTA WARRIORS MUSLIM',
                'duration_days' => 9,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - CHONGQING XI\'AN',
                'product_commission_category' => 'Umum',
                'showprice' => 13900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 850000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN: 12, 14, 16 JUL: 10, 12, 17, 19, 24, 25, 26, 31 AUG: 1, 2, 7, 8, 9, 14, 15, 16, 21, 22, 23, 28, 29, 30 SEP: 1, 3, 4, 5, 6, 8, 10, 11, 12, 13, 15, 17, 18, 19, 20, 22, 24, 25',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 16700000,
                            'Adult Double' => 13900000,
                            'Adult Twin' => 13900000,
                            'Adult Extra Bed' => 13900000,
                            'Child With Bed' => 13900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'OCT: 9, 10, 11, 13, 15, 16, 17, 18, 20, 22, 23, 24, 25, 27, 29, 30, 31',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 16700000,
                            'Adult Double' => 13900000,
                            'Adult Twin' => 13900000,
                            'Adult Extra Bed' => 13900000,
                            'Child With Bed' => 13900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 18, 19, 20, 30 JUL: 2, 3, 5',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 17700000,
                            'Adult Double' => 14900000,
                            'Adult Twin' => 14900000,
                            'Adult Extra Bed' => 14900000,
                            'Child With Bed' => 14900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 21, 23, 25, 26, 27, 28',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 18700000,
                            'Adult Double' => 15900000,
                            'Adult Twin' => 15900000,
                            'Adult Extra Bed' => 15900000,
                            'Child With Bed' => 15900000,
                            'Child No Bed' => 10965000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-005-004',
                'name' => '9D CHONGQING WULONG MUSLIM',
                'description' => '9D CHONGQING WULONG MUSLIM',
                'duration_days' => 9,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - CHONGQING - PENGSHUI - WULONG - FAIRY MOUNTAIN',
                'product_commission_category' => 'Umum',
                'showprice' => 10900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 782000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN: 12, 14, 16 JUL: 10, 12, 17, 19, 24, 25, 26, 31 AUG: 1, 2, 7, 8, 9, 14, 15, 16, 21, 22, 23, 28, 29, 30 SEP: 1, 3, 4, 5, 6, 8, 10, 11, 12, 13, 15, 17, 18, 19, 20, 22, 24, 25',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13100000,
                            'Adult Double' => 10900000,
                            'Adult Twin' => 10900000,
                            'Adult Extra Bed' => 10900000,
                            'Child With Bed' => 10900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'OCT: 9, 10, 11, 13, 15, 16, 17, 18, 20, 22, 23, 24, 25, 27, 29, 30, 31',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 13100000,
                            'Adult Double' => 10900000,
                            'Adult Twin' => 10900000,
                            'Adult Extra Bed' => 10900000,
                            'Child With Bed' => 10900000,
                            'Child No Bed' => 9265000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 18, 19, 20, 30 JUL: 2, 3, 5',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14100000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 21, 23, 25, 26, 27, 28',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 15100000,
                            'Adult Double' => 12900000,
                            'Adult Twin' => 12900000,
                            'Adult Extra Bed' => 12900000,
                            'Child With Bed' => 12900000,
                            'Child No Bed' => 10965000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
            [
                'code' => 'ICT-005-005',
                'name' => '9D ZHANGJIAJIE FURONGZHEN MUSLIM',
                'description' => '9D ZHANGJIAJIE FURONGZHEN MUSLIM',
                'duration_days' => 9,
                'continent' => 'Asia',
                'country' => 'China',
                'region' => 'East Asia',
                'destination' => 'JAKARTA - CHONGQING - QIANJIANG - FENGHUANG - YONGSHUN - ZHANGJIAJIE - PENGSHUI',
                'product_commission_category' => 'Umum',
                'showprice' => 11900000,
                'add_ons' => [
                    'Visa Grup' => 980000,
                    'Tipping' => 782000,
                    'Airport Tax' => 3000000,
                ],
                'price_sets' => [
                    [
                        'departures' => 'JUN: 12, 14, 16 JUL: 10, 12, 17, 19, 24, 25, 26, 31 AUG: 1, 2, 7, 8, 9, 14, 15, 16, 21, 22, 23, 28, 29, 30 SEP: 1, 3, 4, 5, 6, 8, 10, 11, 12, 13, 15, 17, 18, 19, 20, 22, 24, 25',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14700000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'OCT: 9, 10, 11, 13, 15, 16, 17, 18, 20, 22, 23, 24, 25, 27, 29, 30, 31',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 14700000,
                            'Adult Double' => 11900000,
                            'Adult Twin' => 11900000,
                            'Adult Extra Bed' => 11900000,
                            'Child With Bed' => 11900000,
                            'Child No Bed' => 10115000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 18, 19, 20, 30 JUL: 2, 3, 5',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 15700000,
                            'Adult Double' => 12900000,
                            'Adult Twin' => 12900000,
                            'Adult Extra Bed' => 12900000,
                            'Child With Bed' => 12900000,
                            'Child No Bed' => 10965000,
                            'Infant' => 0,
                        ],
                    ],
                    [
                        'departures' => 'JUN: 21, 23, 25, 26, 27, 28',
                        'availability' => 24,
                        'prices' => [
                            'Adult Single' => 16700000,
                            'Adult Double' => 13900000,
                            'Adult Twin' => 13900000,
                            'Adult Extra Bed' => 13900000,
                            'Child With Bed' => 13900000,
                            'Child No Bed' => 11815000,
                            'Infant' => 0,
                        ],
                    ],
                ],
            ],
        ];
    }
}
