/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAiModels200,
  GetAiModelsParams,
  ValidationExceptionResponse
} from '.././model';

import { apiInstance } from '.././api-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Display a listing of the resource
 */
export const getAiModels = (
    params?: GetAiModelsParams,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetAiModels200>(
      {url: `/ai-models`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAiModelsQueryKey = (params?: GetAiModelsParams,) => {
    return [
    `/ai-models`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAiModelsQueryOptions = <TData = Awaited<ReturnType<typeof getAiModels>>, TError = ValidationExceptionResponse>(params?: GetAiModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiModels>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAiModelsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAiModels>>> = ({ signal }) => getAiModels(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAiModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAiModelsQueryResult = NonNullable<Awaited<ReturnType<typeof getAiModels>>>
export type GetAiModelsQueryError = ValidationExceptionResponse


export function useGetAiModels<TData = Awaited<ReturnType<typeof getAiModels>>, TError = ValidationExceptionResponse>(
 params: undefined |  GetAiModelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiModels>>,
          TError,
          Awaited<ReturnType<typeof getAiModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAiModels<TData = Awaited<ReturnType<typeof getAiModels>>, TError = ValidationExceptionResponse>(
 params?: GetAiModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiModels>>,
          TError,
          Awaited<ReturnType<typeof getAiModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAiModels<TData = Awaited<ReturnType<typeof getAiModels>>, TError = ValidationExceptionResponse>(
 params?: GetAiModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiModels>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a listing of the resource
 */

export function useGetAiModels<TData = Awaited<ReturnType<typeof getAiModels>>, TError = ValidationExceptionResponse>(
 params?: GetAiModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiModels>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAiModelsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




