/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetTourCategories200,
  GetTourCategoriesParams,
  ValidationExceptionResponse
} from '.././model';

import { apiInstance } from '.././api-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Display a listing of the resource
 */
export const getTourCategories = (
    params?: GetTourCategoriesParams,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetTourCategories200>(
      {url: `/categories`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetTourCategoriesQueryKey = (params?: GetTourCategoriesParams,) => {
    return [
    `/categories`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTourCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getTourCategories>>, TError = ValidationExceptionResponse>(params?: GetTourCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourCategories>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTourCategoriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTourCategories>>> = ({ signal }) => getTourCategories(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTourCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTourCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getTourCategories>>>
export type GetTourCategoriesQueryError = ValidationExceptionResponse


export function useGetTourCategories<TData = Awaited<ReturnType<typeof getTourCategories>>, TError = ValidationExceptionResponse>(
 params: undefined |  GetTourCategoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTourCategories>>,
          TError,
          Awaited<ReturnType<typeof getTourCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTourCategories<TData = Awaited<ReturnType<typeof getTourCategories>>, TError = ValidationExceptionResponse>(
 params?: GetTourCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTourCategories>>,
          TError,
          Awaited<ReturnType<typeof getTourCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTourCategories<TData = Awaited<ReturnType<typeof getTourCategories>>, TError = ValidationExceptionResponse>(
 params?: GetTourCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourCategories>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a listing of the resource
 */

export function useGetTourCategories<TData = Awaited<ReturnType<typeof getTourCategories>>, TError = ValidationExceptionResponse>(
 params?: GetTourCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourCategories>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTourCategoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




