/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Travelboost
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  CreateCountry201,
  CreateCountryBody,
  GetCountries200,
  GetCountriesParams,
  GetCountryById200,
  UpdateCountry200,
  UpdateCountryBody,
  ValidationExceptionResponse
} from '.././model';

import { apiInstance } from '.././api-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Store a newly created resource in storage
 */
export const createCountry = (
    createCountryBody: CreateCountryBody,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<CreateCountry201>(
      {url: `/countries`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCountryBody, signal
    },
      options);
    }
  


export const getCreateCountryMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCountry>>, TError,{data: CreateCountryBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCountry>>, TError,{data: CreateCountryBody}, TContext> => {

const mutationKey = ['createCountry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCountry>>, {data: CreateCountryBody}> = (props) => {
          const {data} = props ?? {};

          return  createCountry(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCountryMutationResult = NonNullable<Awaited<ReturnType<typeof createCountry>>>
    export type CreateCountryMutationBody = CreateCountryBody
    export type CreateCountryMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Store a newly created resource in storage
 */
export const useCreateCountry = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCountry>>, TError,{data: CreateCountryBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCountry>>,
        TError,
        {data: CreateCountryBody},
        TContext
      > => {

      const mutationOptions = getCreateCountryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Display a listing of the resource
 */
export const getCountries = (
    params?: GetCountriesParams,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetCountries200>(
      {url: `/countries`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCountriesQueryKey = (params?: GetCountriesParams,) => {
    return [
    `/countries`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCountriesQueryOptions = <TData = Awaited<ReturnType<typeof getCountries>>, TError = ValidationExceptionResponse>(params?: GetCountriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountries>>> = ({ signal }) => getCountries(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCountriesQueryResult = NonNullable<Awaited<ReturnType<typeof getCountries>>>
export type GetCountriesQueryError = ValidationExceptionResponse


export function useGetCountries<TData = Awaited<ReturnType<typeof getCountries>>, TError = ValidationExceptionResponse>(
 params: undefined |  GetCountriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountries>>,
          TError,
          Awaited<ReturnType<typeof getCountries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCountries<TData = Awaited<ReturnType<typeof getCountries>>, TError = ValidationExceptionResponse>(
 params?: GetCountriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountries>>,
          TError,
          Awaited<ReturnType<typeof getCountries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCountries<TData = Awaited<ReturnType<typeof getCountries>>, TError = ValidationExceptionResponse>(
 params?: GetCountriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a listing of the resource
 */

export function useGetCountries<TData = Awaited<ReturnType<typeof getCountries>>, TError = ValidationExceptionResponse>(
 params?: GetCountriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCountriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update the specified resource in storage
 */
export const updateCountry = (
    id: string,
    updateCountryBody: UpdateCountryBody,
 options?: SecondParameter<typeof apiInstance>,) => {
      
      
      return apiInstance<UpdateCountry200>(
      {url: `/countries/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCountryBody
    },
      options);
    }
  


export const getUpdateCountryMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCountry>>, TError,{id: string;data: UpdateCountryBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCountry>>, TError,{id: string;data: UpdateCountryBody}, TContext> => {

const mutationKey = ['updateCountry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCountry>>, {id: string;data: UpdateCountryBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCountry(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCountryMutationResult = NonNullable<Awaited<ReturnType<typeof updateCountry>>>
    export type UpdateCountryMutationBody = UpdateCountryBody
    export type UpdateCountryMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update the specified resource in storage
 */
export const useUpdateCountry = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCountry>>, TError,{id: string;data: UpdateCountryBody}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCountry>>,
        TError,
        {id: string;data: UpdateCountryBody},
        TContext
      > => {

      const mutationOptions = getUpdateCountryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Remove the specified resource from storage
 */
export const deleteCountry = (
    id: string,
 options?: SecondParameter<typeof apiInstance>,) => {
      
      
      return apiInstance<void>(
      {url: `/countries/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteCountryMutationOptions = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCountry>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCountry>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteCountry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCountry>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteCountry(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCountryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCountry>>>
    
    export type DeleteCountryMutationError = AuthenticationExceptionResponse

    /**
 * @summary Remove the specified resource from storage
 */
export const useDeleteCountry = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCountry>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCountry>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteCountryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Display the specified resource
 */
export const getCountryById = (
    id: string,
 options?: SecondParameter<typeof apiInstance>,signal?: AbortSignal
) => {
      
      
      return apiInstance<GetCountryById200>(
      {url: `/countries/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCountryByIdQueryKey = (id?: string,) => {
    return [
    `/countries/${id}`
    ] as const;
    }

    
export const getGetCountryByIdQueryOptions = <TData = Awaited<ReturnType<typeof getCountryById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountryById>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountryByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountryById>>> = ({ signal }) => getCountryById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountryById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCountryByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCountryById>>>
export type GetCountryByIdQueryError = unknown


export function useGetCountryById<TData = Awaited<ReturnType<typeof getCountryById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountryById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountryById>>,
          TError,
          Awaited<ReturnType<typeof getCountryById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCountryById<TData = Awaited<ReturnType<typeof getCountryById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountryById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountryById>>,
          TError,
          Awaited<ReturnType<typeof getCountryById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCountryById<TData = Awaited<ReturnType<typeof getCountryById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountryById>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display the specified resource
 */

export function useGetCountryById<TData = Awaited<ReturnType<typeof getCountryById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountryById>>, TError, TData>>, request?: SecondParameter<typeof apiInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCountryByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




